/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A brand query.
 **/
@ApiModel(description = "A brand query.")
public class BrandModelsBrandQuery {
  
  @SerializedName("CreatedAfter")
  private Date createdAfter = null;
  @SerializedName("BrandIds")
  private List<Integer> brandIds = null;
  @SerializedName("ExternalIds")
  private List<String> externalIds = null;

  /**
   * Limits query to brands created after the specified date.
   **/
  @ApiModelProperty(value = "Limits query to brands created after the specified date.")
  public Date getCreatedAfter() {
    return createdAfter;
  }
  public void setCreatedAfter(Date createdAfter) {
    this.createdAfter = createdAfter;
  }

  /**
   * Limits query to only include the supplied brand ids.
   **/
  @ApiModelProperty(value = "Limits query to only include the supplied brand ids.")
  public List<Integer> getBrandIds() {
    return brandIds;
  }
  public void setBrandIds(List<Integer> brandIds) {
    this.brandIds = brandIds;
  }

  /**
   * Limits query to externalIds
   **/
  @ApiModelProperty(value = "Limits query to externalIds")
  public List<String> getExternalIds() {
    return externalIds;
  }
  public void setExternalIds(List<String> externalIds) {
    this.externalIds = externalIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrandModelsBrandQuery brandModelsBrandQuery = (BrandModelsBrandQuery) o;
    return (this.createdAfter == null ? brandModelsBrandQuery.createdAfter == null : this.createdAfter.equals(brandModelsBrandQuery.createdAfter)) &&
        (this.brandIds == null ? brandModelsBrandQuery.brandIds == null : this.brandIds.equals(brandModelsBrandQuery.brandIds)) &&
        (this.externalIds == null ? brandModelsBrandQuery.externalIds == null : this.externalIds.equals(brandModelsBrandQuery.externalIds));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.createdAfter == null ? 0: this.createdAfter.hashCode());
    result = 31 * result + (this.brandIds == null ? 0: this.brandIds.hashCode());
    result = 31 * result + (this.externalIds == null ? 0: this.externalIds.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrandModelsBrandQuery {\n");
    
    sb.append("  createdAfter: ").append(createdAfter).append("\n");
    sb.append("  brandIds: ").append(brandIds).append("\n");
    sb.append("  externalIds: ").append(externalIds).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
