/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class MarketModelsMarket {
  
  @SerializedName("Id")
  private Integer id = null;
  @SerializedName("Name")
  private String name = null;
  @SerializedName("DisplayName")
  private String displayName = null;
  @SerializedName("Currency")
  private String currency = null;
  @SerializedName("VatRate")
  private Double vatRate = null;
  @SerializedName("MarketPrefix")
  private String marketPrefix = null;
  @SerializedName("CountryId")
  private Integer countryId = null;
  @SerializedName("CurrencyId")
  private Integer currencyId = null;
  @SerializedName("CurrencyRate")
  private Double currencyRate = null;
  @SerializedName("LanguageId")
  private Integer languageId = null;
  @SerializedName("Language")
  private String language = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getVatRate() {
    return vatRate;
  }
  public void setVatRate(Double vatRate) {
    this.vatRate = vatRate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMarketPrefix() {
    return marketPrefix;
  }
  public void setMarketPrefix(String marketPrefix) {
    this.marketPrefix = marketPrefix;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCountryId() {
    return countryId;
  }
  public void setCountryId(Integer countryId) {
    this.countryId = countryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCurrencyId() {
    return currencyId;
  }
  public void setCurrencyId(Integer currencyId) {
    this.currencyId = currencyId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getCurrencyRate() {
    return currencyRate;
  }
  public void setCurrencyRate(Double currencyRate) {
    this.currencyRate = currencyRate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getLanguageId() {
    return languageId;
  }
  public void setLanguageId(Integer languageId) {
    this.languageId = languageId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLanguage() {
    return language;
  }
  public void setLanguage(String language) {
    this.language = language;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketModelsMarket marketModelsMarket = (MarketModelsMarket) o;
    return (this.id == null ? marketModelsMarket.id == null : this.id.equals(marketModelsMarket.id)) &&
        (this.name == null ? marketModelsMarket.name == null : this.name.equals(marketModelsMarket.name)) &&
        (this.displayName == null ? marketModelsMarket.displayName == null : this.displayName.equals(marketModelsMarket.displayName)) &&
        (this.currency == null ? marketModelsMarket.currency == null : this.currency.equals(marketModelsMarket.currency)) &&
        (this.vatRate == null ? marketModelsMarket.vatRate == null : this.vatRate.equals(marketModelsMarket.vatRate)) &&
        (this.marketPrefix == null ? marketModelsMarket.marketPrefix == null : this.marketPrefix.equals(marketModelsMarket.marketPrefix)) &&
        (this.countryId == null ? marketModelsMarket.countryId == null : this.countryId.equals(marketModelsMarket.countryId)) &&
        (this.currencyId == null ? marketModelsMarket.currencyId == null : this.currencyId.equals(marketModelsMarket.currencyId)) &&
        (this.currencyRate == null ? marketModelsMarket.currencyRate == null : this.currencyRate.equals(marketModelsMarket.currencyRate)) &&
        (this.languageId == null ? marketModelsMarket.languageId == null : this.languageId.equals(marketModelsMarket.languageId)) &&
        (this.language == null ? marketModelsMarket.language == null : this.language.equals(marketModelsMarket.language));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.vatRate == null ? 0: this.vatRate.hashCode());
    result = 31 * result + (this.marketPrefix == null ? 0: this.marketPrefix.hashCode());
    result = 31 * result + (this.countryId == null ? 0: this.countryId.hashCode());
    result = 31 * result + (this.currencyId == null ? 0: this.currencyId.hashCode());
    result = 31 * result + (this.currencyRate == null ? 0: this.currencyRate.hashCode());
    result = 31 * result + (this.languageId == null ? 0: this.languageId.hashCode());
    result = 31 * result + (this.language == null ? 0: this.language.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketModelsMarket {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  vatRate: ").append(vatRate).append("\n");
    sb.append("  marketPrefix: ").append(marketPrefix).append("\n");
    sb.append("  countryId: ").append(countryId).append("\n");
    sb.append("  currencyId: ").append(currencyId).append("\n");
    sb.append("  currencyRate: ").append(currencyRate).append("\n");
    sb.append("  languageId: ").append(languageId).append("\n");
    sb.append("  language: ").append(language).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
