/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Date;
import java.util.UUID;
import org.openapitools.client.model.OrderRefundRow;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderRefund {
  
  @SerializedName("RefundId")
  private UUID refundId = null;
  @SerializedName("RefundInstanceId")
  private Integer refundInstanceId = null;
  @SerializedName("OrderId")
  private Integer orderId = null;
  @SerializedName("ExternalOrderId")
  private String externalOrderId = null;
  @SerializedName("ExternalId")
  private String externalId = null;
  @SerializedName("Reference")
  private String reference = null;
  @SerializedName("Description")
  private String description = null;
  @SerializedName("ProcessedOn")
  private Date processedOn = null;
  @SerializedName("RefundedItemTotal")
  private Double refundedItemTotal = null;
  @SerializedName("RefundedShippingFee")
  private Double refundedShippingFee = null;
  @SerializedName("RefundedPaymentFee")
  private Double refundedPaymentFee = null;
  @SerializedName("RefundedDiscount")
  private Double refundedDiscount = null;
  @SerializedName("RefundedBalance")
  private Double refundedBalance = null;
  @SerializedName("VatRate")
  private Double vatRate = null;
  @SerializedName("PaymentName")
  private String paymentName = null;
  @SerializedName("Locale")
  private String locale = null;
  @SerializedName("Rows")
  private List<OrderRefundRow> rows = null;
  @SerializedName("OrderTransactionId")
  private String orderTransactionId = null;
  @SerializedName("SecondaryOrderTransactionId")
  private String secondaryOrderTransactionId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getRefundId() {
    return refundId;
  }
  public void setRefundId(UUID refundId) {
    this.refundId = refundId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getRefundInstanceId() {
    return refundInstanceId;
  }
  public void setRefundInstanceId(Integer refundInstanceId) {
    this.refundInstanceId = refundInstanceId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOrderId() {
    return orderId;
  }
  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExternalOrderId() {
    return externalOrderId;
  }
  public void setExternalOrderId(String externalOrderId) {
    this.externalOrderId = externalOrderId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExternalId() {
    return externalId;
  }
  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getReference() {
    return reference;
  }
  public void setReference(String reference) {
    this.reference = reference;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getProcessedOn() {
    return processedOn;
  }
  public void setProcessedOn(Date processedOn) {
    this.processedOn = processedOn;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getRefundedItemTotal() {
    return refundedItemTotal;
  }
  public void setRefundedItemTotal(Double refundedItemTotal) {
    this.refundedItemTotal = refundedItemTotal;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getRefundedShippingFee() {
    return refundedShippingFee;
  }
  public void setRefundedShippingFee(Double refundedShippingFee) {
    this.refundedShippingFee = refundedShippingFee;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getRefundedPaymentFee() {
    return refundedPaymentFee;
  }
  public void setRefundedPaymentFee(Double refundedPaymentFee) {
    this.refundedPaymentFee = refundedPaymentFee;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getRefundedDiscount() {
    return refundedDiscount;
  }
  public void setRefundedDiscount(Double refundedDiscount) {
    this.refundedDiscount = refundedDiscount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getRefundedBalance() {
    return refundedBalance;
  }
  public void setRefundedBalance(Double refundedBalance) {
    this.refundedBalance = refundedBalance;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getVatRate() {
    return vatRate;
  }
  public void setVatRate(Double vatRate) {
    this.vatRate = vatRate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPaymentName() {
    return paymentName;
  }
  public void setPaymentName(String paymentName) {
    this.paymentName = paymentName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLocale() {
    return locale;
  }
  public void setLocale(String locale) {
    this.locale = locale;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<OrderRefundRow> getRows() {
    return rows;
  }
  public void setRows(List<OrderRefundRow> rows) {
    this.rows = rows;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrderTransactionId() {
    return orderTransactionId;
  }
  public void setOrderTransactionId(String orderTransactionId) {
    this.orderTransactionId = orderTransactionId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSecondaryOrderTransactionId() {
    return secondaryOrderTransactionId;
  }
  public void setSecondaryOrderTransactionId(String secondaryOrderTransactionId) {
    this.secondaryOrderTransactionId = secondaryOrderTransactionId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderRefund orderRefund = (OrderRefund) o;
    return (this.refundId == null ? orderRefund.refundId == null : this.refundId.equals(orderRefund.refundId)) &&
        (this.refundInstanceId == null ? orderRefund.refundInstanceId == null : this.refundInstanceId.equals(orderRefund.refundInstanceId)) &&
        (this.orderId == null ? orderRefund.orderId == null : this.orderId.equals(orderRefund.orderId)) &&
        (this.externalOrderId == null ? orderRefund.externalOrderId == null : this.externalOrderId.equals(orderRefund.externalOrderId)) &&
        (this.externalId == null ? orderRefund.externalId == null : this.externalId.equals(orderRefund.externalId)) &&
        (this.reference == null ? orderRefund.reference == null : this.reference.equals(orderRefund.reference)) &&
        (this.description == null ? orderRefund.description == null : this.description.equals(orderRefund.description)) &&
        (this.processedOn == null ? orderRefund.processedOn == null : this.processedOn.equals(orderRefund.processedOn)) &&
        (this.refundedItemTotal == null ? orderRefund.refundedItemTotal == null : this.refundedItemTotal.equals(orderRefund.refundedItemTotal)) &&
        (this.refundedShippingFee == null ? orderRefund.refundedShippingFee == null : this.refundedShippingFee.equals(orderRefund.refundedShippingFee)) &&
        (this.refundedPaymentFee == null ? orderRefund.refundedPaymentFee == null : this.refundedPaymentFee.equals(orderRefund.refundedPaymentFee)) &&
        (this.refundedDiscount == null ? orderRefund.refundedDiscount == null : this.refundedDiscount.equals(orderRefund.refundedDiscount)) &&
        (this.refundedBalance == null ? orderRefund.refundedBalance == null : this.refundedBalance.equals(orderRefund.refundedBalance)) &&
        (this.vatRate == null ? orderRefund.vatRate == null : this.vatRate.equals(orderRefund.vatRate)) &&
        (this.paymentName == null ? orderRefund.paymentName == null : this.paymentName.equals(orderRefund.paymentName)) &&
        (this.locale == null ? orderRefund.locale == null : this.locale.equals(orderRefund.locale)) &&
        (this.rows == null ? orderRefund.rows == null : this.rows.equals(orderRefund.rows)) &&
        (this.orderTransactionId == null ? orderRefund.orderTransactionId == null : this.orderTransactionId.equals(orderRefund.orderTransactionId)) &&
        (this.secondaryOrderTransactionId == null ? orderRefund.secondaryOrderTransactionId == null : this.secondaryOrderTransactionId.equals(orderRefund.secondaryOrderTransactionId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.refundId == null ? 0: this.refundId.hashCode());
    result = 31 * result + (this.refundInstanceId == null ? 0: this.refundInstanceId.hashCode());
    result = 31 * result + (this.orderId == null ? 0: this.orderId.hashCode());
    result = 31 * result + (this.externalOrderId == null ? 0: this.externalOrderId.hashCode());
    result = 31 * result + (this.externalId == null ? 0: this.externalId.hashCode());
    result = 31 * result + (this.reference == null ? 0: this.reference.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.processedOn == null ? 0: this.processedOn.hashCode());
    result = 31 * result + (this.refundedItemTotal == null ? 0: this.refundedItemTotal.hashCode());
    result = 31 * result + (this.refundedShippingFee == null ? 0: this.refundedShippingFee.hashCode());
    result = 31 * result + (this.refundedPaymentFee == null ? 0: this.refundedPaymentFee.hashCode());
    result = 31 * result + (this.refundedDiscount == null ? 0: this.refundedDiscount.hashCode());
    result = 31 * result + (this.refundedBalance == null ? 0: this.refundedBalance.hashCode());
    result = 31 * result + (this.vatRate == null ? 0: this.vatRate.hashCode());
    result = 31 * result + (this.paymentName == null ? 0: this.paymentName.hashCode());
    result = 31 * result + (this.locale == null ? 0: this.locale.hashCode());
    result = 31 * result + (this.rows == null ? 0: this.rows.hashCode());
    result = 31 * result + (this.orderTransactionId == null ? 0: this.orderTransactionId.hashCode());
    result = 31 * result + (this.secondaryOrderTransactionId == null ? 0: this.secondaryOrderTransactionId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRefund {\n");
    
    sb.append("  refundId: ").append(refundId).append("\n");
    sb.append("  refundInstanceId: ").append(refundInstanceId).append("\n");
    sb.append("  orderId: ").append(orderId).append("\n");
    sb.append("  externalOrderId: ").append(externalOrderId).append("\n");
    sb.append("  externalId: ").append(externalId).append("\n");
    sb.append("  reference: ").append(reference).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  processedOn: ").append(processedOn).append("\n");
    sb.append("  refundedItemTotal: ").append(refundedItemTotal).append("\n");
    sb.append("  refundedShippingFee: ").append(refundedShippingFee).append("\n");
    sb.append("  refundedPaymentFee: ").append(refundedPaymentFee).append("\n");
    sb.append("  refundedDiscount: ").append(refundedDiscount).append("\n");
    sb.append("  refundedBalance: ").append(refundedBalance).append("\n");
    sb.append("  vatRate: ").append(vatRate).append("\n");
    sb.append("  paymentName: ").append(paymentName).append("\n");
    sb.append("  locale: ").append(locale).append("\n");
    sb.append("  rows: ").append(rows).append("\n");
    sb.append("  orderTransactionId: ").append(orderTransactionId).append("\n");
    sb.append("  secondaryOrderTransactionId: ").append(secondaryOrderTransactionId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
