/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Data carrier for a shipping detail
 **/
@ApiModel(description = "Data carrier for a shipping detail")
public class OrderModelsShippingDetail {
  
  @SerializedName("Id")
  private Integer id = null;
  @SerializedName("ShippingId")
  private Integer shippingId = null;
  @SerializedName("Name")
  private String name = null;
  @SerializedName("ParcelNumber")
  private String parcelNumber = null;
  @SerializedName("ShippingDate")
  private Date shippingDate = null;
  @SerializedName("TrackingUrl")
  private String trackingUrl = null;
  @SerializedName("ExternalDeliveryOptionId")
  private String externalDeliveryOptionId = null;
  @SerializedName("ExternalServiceId")
  private String externalServiceId = null;
  @SerializedName("ExternalCarrierId")
  private String externalCarrierId = null;
  @SerializedName("PickupPoint")
  private String pickupPoint = null;

  /**
   * Unique identifier for this shipping detail
   **/
  @ApiModelProperty(value = "Unique identifier for this shipping detail")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * Id of the sipping method
   **/
  @ApiModelProperty(value = "Id of the sipping method")
  public Integer getShippingId() {
    return shippingId;
  }
  public void setShippingId(Integer shippingId) {
    this.shippingId = shippingId;
  }

  /**
   * Name of the shipping method
   **/
  @ApiModelProperty(value = "Name of the shipping method")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Parcel number (tracking number)
   **/
  @ApiModelProperty(value = "Parcel number (tracking number)")
  public String getParcelNumber() {
    return parcelNumber;
  }
  public void setParcelNumber(String parcelNumber) {
    this.parcelNumber = parcelNumber;
  }

  /**
   * Shipping date
   **/
  @ApiModelProperty(value = "Shipping date")
  public Date getShippingDate() {
    return shippingDate;
  }
  public void setShippingDate(Date shippingDate) {
    this.shippingDate = shippingDate;
  }

  /**
   * Tracking URL
   **/
  @ApiModelProperty(value = "Tracking URL")
  public String getTrackingUrl() {
    return trackingUrl;
  }
  public void setTrackingUrl(String trackingUrl) {
    this.trackingUrl = trackingUrl;
  }

  /**
   * Delivery option id of the external shipping provider
   **/
  @ApiModelProperty(value = "Delivery option id of the external shipping provider")
  public String getExternalDeliveryOptionId() {
    return externalDeliveryOptionId;
  }
  public void setExternalDeliveryOptionId(String externalDeliveryOptionId) {
    this.externalDeliveryOptionId = externalDeliveryOptionId;
  }

  /**
   * Service id of the external shipping provider
   **/
  @ApiModelProperty(value = "Service id of the external shipping provider")
  public String getExternalServiceId() {
    return externalServiceId;
  }
  public void setExternalServiceId(String externalServiceId) {
    this.externalServiceId = externalServiceId;
  }

  /**
   * Carrier id of the external shipping provider
   **/
  @ApiModelProperty(value = "Carrier id of the external shipping provider")
  public String getExternalCarrierId() {
    return externalCarrierId;
  }
  public void setExternalCarrierId(String externalCarrierId) {
    this.externalCarrierId = externalCarrierId;
  }

  /**
   * Pickup point
   **/
  @ApiModelProperty(value = "Pickup point")
  public String getPickupPoint() {
    return pickupPoint;
  }
  public void setPickupPoint(String pickupPoint) {
    this.pickupPoint = pickupPoint;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderModelsShippingDetail orderModelsShippingDetail = (OrderModelsShippingDetail) o;
    return (this.id == null ? orderModelsShippingDetail.id == null : this.id.equals(orderModelsShippingDetail.id)) &&
        (this.shippingId == null ? orderModelsShippingDetail.shippingId == null : this.shippingId.equals(orderModelsShippingDetail.shippingId)) &&
        (this.name == null ? orderModelsShippingDetail.name == null : this.name.equals(orderModelsShippingDetail.name)) &&
        (this.parcelNumber == null ? orderModelsShippingDetail.parcelNumber == null : this.parcelNumber.equals(orderModelsShippingDetail.parcelNumber)) &&
        (this.shippingDate == null ? orderModelsShippingDetail.shippingDate == null : this.shippingDate.equals(orderModelsShippingDetail.shippingDate)) &&
        (this.trackingUrl == null ? orderModelsShippingDetail.trackingUrl == null : this.trackingUrl.equals(orderModelsShippingDetail.trackingUrl)) &&
        (this.externalDeliveryOptionId == null ? orderModelsShippingDetail.externalDeliveryOptionId == null : this.externalDeliveryOptionId.equals(orderModelsShippingDetail.externalDeliveryOptionId)) &&
        (this.externalServiceId == null ? orderModelsShippingDetail.externalServiceId == null : this.externalServiceId.equals(orderModelsShippingDetail.externalServiceId)) &&
        (this.externalCarrierId == null ? orderModelsShippingDetail.externalCarrierId == null : this.externalCarrierId.equals(orderModelsShippingDetail.externalCarrierId)) &&
        (this.pickupPoint == null ? orderModelsShippingDetail.pickupPoint == null : this.pickupPoint.equals(orderModelsShippingDetail.pickupPoint));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.shippingId == null ? 0: this.shippingId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.parcelNumber == null ? 0: this.parcelNumber.hashCode());
    result = 31 * result + (this.shippingDate == null ? 0: this.shippingDate.hashCode());
    result = 31 * result + (this.trackingUrl == null ? 0: this.trackingUrl.hashCode());
    result = 31 * result + (this.externalDeliveryOptionId == null ? 0: this.externalDeliveryOptionId.hashCode());
    result = 31 * result + (this.externalServiceId == null ? 0: this.externalServiceId.hashCode());
    result = 31 * result + (this.externalCarrierId == null ? 0: this.externalCarrierId.hashCode());
    result = 31 * result + (this.pickupPoint == null ? 0: this.pickupPoint.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderModelsShippingDetail {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  shippingId: ").append(shippingId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  parcelNumber: ").append(parcelNumber).append("\n");
    sb.append("  shippingDate: ").append(shippingDate).append("\n");
    sb.append("  trackingUrl: ").append(trackingUrl).append("\n");
    sb.append("  externalDeliveryOptionId: ").append(externalDeliveryOptionId).append("\n");
    sb.append("  externalServiceId: ").append(externalServiceId).append("\n");
    sb.append("  externalCarrierId: ").append(externalCarrierId).append("\n");
    sb.append("  pickupPoint: ").append(pickupPoint).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
