/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Date;
import java.util.Map;
import java.util.UUID;
import org.openapitools.client.model.OrderModelsAddress;
import org.openapitools.client.model.OrderModelsOrderRow;
import org.openapitools.client.model.OrderModelsPaymentDetail;
import org.openapitools.client.model.OrderModelsRefund;
import org.openapitools.client.model.OrderModelsShippingDetail;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Data carrier for an order.
 **/
@ApiModel(description = "Data carrier for an order.")
public class OrderModelsOrder {
  
  @SerializedName("Id")
  private Integer id = null;
  @SerializedName("ExternalId")
  private String externalId = null;
  @SerializedName("PersonalId")
  private String personalId = null;
  @SerializedName("CustomerId")
  private Integer customerId = null;
  @SerializedName("CustomerTypeId")
  private Integer customerTypeId = null;
  @SerializedName("CreatedAt")
  private Date createdAt = null;
  @SerializedName("UpdatedAt")
  private Date updatedAt = null;
  @SerializedName("CompletedAt")
  private Date completedAt = null;
  @SerializedName("Status")
  private String status = null;
  @SerializedName("Currency")
  private String currency = null;
  @SerializedName("CurrencyRate")
  private Double currencyRate = null;
  @SerializedName("MarketId")
  private Integer marketId = null;
  @SerializedName("MarketName")
  private String marketName = null;
  @SerializedName("Language")
  private String language = null;
  @SerializedName("OrderTotal")
  private Double orderTotal = null;
  @SerializedName("ExpectedSum")
  private Double expectedSum = null;
  @SerializedName("VATTotal")
  private Double vATTotal = null;
  @SerializedName("OrderValueIncVat")
  private Double orderValueIncVat = null;
  @SerializedName("OrderValueExVat")
  private Double orderValueExVat = null;
  @SerializedName("ItemValueIncVat")
  private Double itemValueIncVat = null;
  @SerializedName("ItemValueExVat")
  private Double itemValueExVat = null;
  @SerializedName("Discount")
  private Double discount = null;
  @SerializedName("DiscountExVat")
  private Double discountExVat = null;
  @SerializedName("FromBalance")
  private Double fromBalance = null;
  @SerializedName("ShippingFee")
  private Double shippingFee = null;
  @SerializedName("ShippingFeeExVat")
  private Double shippingFeeExVat = null;
  @SerializedName("PaymentFee")
  private Double paymentFee = null;
  @SerializedName("PaymentFeeExVat")
  private Double paymentFeeExVat = null;
  @SerializedName("Message")
  private String message = null;
  @SerializedName("OrderMessages")
  private List<String> orderMessages = null;
  @SerializedName("PaymentDetails")
  private List<OrderModelsPaymentDetail> paymentDetails = null;
  @SerializedName("ShippingDetails")
  private List<OrderModelsShippingDetail> shippingDetails = null;
  @SerializedName("ShippingAddress")
  private OrderModelsAddress shippingAddress = null;
  @SerializedName("BillingAddress")
  private OrderModelsAddress billingAddress = null;
  @SerializedName("Rows")
  private List<OrderModelsOrderRow> rows = null;
  @SerializedName("Refunds")
  private List<OrderModelsRefund> refunds = null;
  @SerializedName("Ip")
  private String ip = null;
  @SerializedName("UserAgent")
  private String userAgent = null;
  @SerializedName("ServiceLocation")
  private String serviceLocation = null;
  @SerializedName("CampaignCode")
  private String campaignCode = null;
  @SerializedName("CampaignCodeId")
  private Integer campaignCodeId = null;
  @SerializedName("Percent")
  private Integer percent = null;
  @SerializedName("DesiredDeliveryDate")
  private Date desiredDeliveryDate = null;
  @SerializedName("Gender")
  private Boolean gender = null;
  @SerializedName("CartId")
  private Integer cartId = null;
  @SerializedName("SessionId")
  private String sessionId = null;
  public enum ExternalOrderStatusEnum {
     0,  10,  20,  30,  40, 
  };
  @SerializedName("ExternalOrderStatus")
  private ExternalOrderStatusEnum externalOrderStatus = null;
  @SerializedName("CampaignIds")
  private List<String> campaignIds = null;
  @SerializedName("CampaignNames")
  private List<String> campaignNames = null;
  @SerializedName("MetaData")
  private Map<String, String> metaData = null;
  @SerializedName("PublicId")
  private UUID publicId = null;

  /**
   * The unique identifier for this order.
   **/
  @ApiModelProperty(value = "The unique identifier for this order.")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * The unique external identifier for this order.
   **/
  @ApiModelProperty(value = "The unique external identifier for this order.")
  public String getExternalId() {
    return externalId;
  }
  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  /**
   * The social security number, or organisational number of the customer.
   **/
  @ApiModelProperty(value = "The social security number, or organisational number of the customer.")
  public String getPersonalId() {
    return personalId;
  }
  public void setPersonalId(String personalId) {
    this.personalId = personalId;
  }

  /**
   * The unique identifier of the customer placing this order.
   **/
  @ApiModelProperty(value = "The unique identifier of the customer placing this order.")
  public Integer getCustomerId() {
    return customerId;
  }
  public void setCustomerId(Integer customerId) {
    this.customerId = customerId;
  }

  /**
   * Customer type. Usually 1 for private customers and 2 for companies. This field is customer specific
   **/
  @ApiModelProperty(value = "Customer type. Usually 1 for private customers and 2 for companies. This field is customer specific")
  public Integer getCustomerTypeId() {
    return customerTypeId;
  }
  public void setCustomerTypeId(Integer customerTypeId) {
    this.customerTypeId = customerTypeId;
  }

  /**
   * Datetime when the order was created.
   **/
  @ApiModelProperty(value = "Datetime when the order was created.")
  public Date getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * Datetime when the order was last updated.
   **/
  @ApiModelProperty(value = "Datetime when the order was last updated.")
  public Date getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   * The DateTime when the order was completed (delivered, payed).
   **/
  @ApiModelProperty(value = "The DateTime when the order was completed (delivered, payed).")
  public Date getCompletedAt() {
    return completedAt;
  }
  public void setCompletedAt(Date completedAt) {
    this.completedAt = completedAt;
  }

  /**
   * The order status. Possbile values: cancelled, on-hold, inactive, refunded, partial,  pending-payment, out-of-stock, backorder, completed, pending.
   **/
  @ApiModelProperty(value = "The order status. Possbile values: cancelled, on-hold, inactive, refunded, partial,  pending-payment, out-of-stock, backorder, completed, pending.")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * ISO Currency code.
   **/
  @ApiModelProperty(value = "ISO Currency code.")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }

  /**
   * The Currency Rate to SEK.
   **/
  @ApiModelProperty(value = "The Currency Rate to SEK.")
  public Double getCurrencyRate() {
    return currencyRate;
  }
  public void setCurrencyRate(Double currencyRate) {
    this.currencyRate = currencyRate;
  }

  /**
   * The unique identifier for the market this order originates from.
   **/
  @ApiModelProperty(value = "The unique identifier for the market this order originates from.")
  public Integer getMarketId() {
    return marketId;
  }
  public void setMarketId(Integer marketId) {
    this.marketId = marketId;
  }

  /**
   * The market name. Usually this is the equal to the site name.
   **/
  @ApiModelProperty(value = "The market name. Usually this is the equal to the site name.")
  public String getMarketName() {
    return marketName;
  }
  public void setMarketName(String marketName) {
    this.marketName = marketName;
  }

  /**
   * Two-letter Language code.
   **/
  @ApiModelProperty(value = "Two-letter Language code.")
  public String getLanguage() {
    return language;
  }
  public void setLanguage(String language) {
    this.language = language;
  }

  /**
   * Order total.
   **/
  @ApiModelProperty(value = "Order total.")
  public Double getOrderTotal() {
    return orderTotal;
  }
  public void setOrderTotal(Double orderTotal) {
    this.orderTotal = orderTotal;
  }

  /**
   * Expected total sum to be paid after discount and balance.   <para>The value is usually taken directly from the payment provider and represents the actual reserved amount.</para><para>If this differs from OrderTotal, actions should be taken to ensure they match. This usually happens due to rounding.</para>
   **/
  @ApiModelProperty(value = "Expected total sum to be paid after discount and balance.   <para>The value is usually taken directly from the payment provider and represents the actual reserved amount.</para><para>If this differs from OrderTotal, actions should be taken to ensure they match. This usually happens due to rounding.</para>")
  public Double getExpectedSum() {
    return expectedSum;
  }
  public void setExpectedSum(Double expectedSum) {
    this.expectedSum = expectedSum;
  }

  /**
   * Order VAT total.
   **/
  @ApiModelProperty(value = "Order VAT total.")
  public Double getVATTotal() {
    return vATTotal;
  }
  public void setVATTotal(Double vATTotal) {
    this.vATTotal = vATTotal;
  }

  /**
   * Order value inc vat after discount but before balance
   **/
  @ApiModelProperty(value = "Order value inc vat after discount but before balance")
  public Double getOrderValueIncVat() {
    return orderValueIncVat;
  }
  public void setOrderValueIncVat(Double orderValueIncVat) {
    this.orderValueIncVat = orderValueIncVat;
  }

  /**
   * Order value ex vat after discount but before balance
   **/
  @ApiModelProperty(value = "Order value ex vat after discount but before balance")
  public Double getOrderValueExVat() {
    return orderValueExVat;
  }
  public void setOrderValueExVat(Double orderValueExVat) {
    this.orderValueExVat = orderValueExVat;
  }

  /**
   * Item value inc vat excluding fees and discount
   **/
  @ApiModelProperty(value = "Item value inc vat excluding fees and discount")
  public Double getItemValueIncVat() {
    return itemValueIncVat;
  }
  public void setItemValueIncVat(Double itemValueIncVat) {
    this.itemValueIncVat = itemValueIncVat;
  }

  /**
   * Item value ex vat excluding fees and discount
   **/
  @ApiModelProperty(value = "Item value ex vat excluding fees and discount")
  public Double getItemValueExVat() {
    return itemValueExVat;
  }
  public void setItemValueExVat(Double itemValueExVat) {
    this.itemValueExVat = itemValueExVat;
  }

  /**
   * Total discount inc vat.
   **/
  @ApiModelProperty(value = "Total discount inc vat.")
  public Double getDiscount() {
    return discount;
  }
  public void setDiscount(Double discount) {
    this.discount = discount;
  }

  /**
   * Total discount ex vat.
   **/
  @ApiModelProperty(value = "Total discount ex vat.")
  public Double getDiscountExVat() {
    return discountExVat;
  }
  public void setDiscountExVat(Double discountExVat) {
    this.discountExVat = discountExVat;
  }

  /**
   * The amount which was withdrawn from the customers balance inc vat.
   **/
  @ApiModelProperty(value = "The amount which was withdrawn from the customers balance inc vat.")
  public Double getFromBalance() {
    return fromBalance;
  }
  public void setFromBalance(Double fromBalance) {
    this.fromBalance = fromBalance;
  }

  /**
   * Shipping fee inc vat.
   **/
  @ApiModelProperty(value = "Shipping fee inc vat.")
  public Double getShippingFee() {
    return shippingFee;
  }
  public void setShippingFee(Double shippingFee) {
    this.shippingFee = shippingFee;
  }

  /**
   * Shipping fee ex vat.
   **/
  @ApiModelProperty(value = "Shipping fee ex vat.")
  public Double getShippingFeeExVat() {
    return shippingFeeExVat;
  }
  public void setShippingFeeExVat(Double shippingFeeExVat) {
    this.shippingFeeExVat = shippingFeeExVat;
  }

  /**
   * Payment fee inc vat.
   **/
  @ApiModelProperty(value = "Payment fee inc vat.")
  public Double getPaymentFee() {
    return paymentFee;
  }
  public void setPaymentFee(Double paymentFee) {
    this.paymentFee = paymentFee;
  }

  /**
   * Payment fee ex vat.
   **/
  @ApiModelProperty(value = "Payment fee ex vat.")
  public Double getPaymentFeeExVat() {
    return paymentFeeExVat;
  }
  public void setPaymentFeeExVat(Double paymentFeeExVat) {
    this.paymentFeeExVat = paymentFeeExVat;
  }

  /**
   * Order message. Can contain instructions from customer or added details about the order.
   **/
  @ApiModelProperty(value = "Order message. Can contain instructions from customer or added details about the order.")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   * Internal order messages. Can contain internal details about the order.
   **/
  @ApiModelProperty(value = "Internal order messages. Can contain internal details about the order.")
  public List<String> getOrderMessages() {
    return orderMessages;
  }
  public void setOrderMessages(List<String> orderMessages) {
    this.orderMessages = orderMessages;
  }

  /**
   * List of payment details <seealso cref=\"T:Order.Models.PaymentDetail\" />.
   **/
  @ApiModelProperty(value = "List of payment details <seealso cref=\"T:Order.Models.PaymentDetail\" />.")
  public List<OrderModelsPaymentDetail> getPaymentDetails() {
    return paymentDetails;
  }
  public void setPaymentDetails(List<OrderModelsPaymentDetail> paymentDetails) {
    this.paymentDetails = paymentDetails;
  }

  /**
   * List of shipping details <seealso cref=\"T:Order.Models.ShippingDetail\" />.
   **/
  @ApiModelProperty(value = "List of shipping details <seealso cref=\"T:Order.Models.ShippingDetail\" />.")
  public List<OrderModelsShippingDetail> getShippingDetails() {
    return shippingDetails;
  }
  public void setShippingDetails(List<OrderModelsShippingDetail> shippingDetails) {
    this.shippingDetails = shippingDetails;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public OrderModelsAddress getShippingAddress() {
    return shippingAddress;
  }
  public void setShippingAddress(OrderModelsAddress shippingAddress) {
    this.shippingAddress = shippingAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public OrderModelsAddress getBillingAddress() {
    return billingAddress;
  }
  public void setBillingAddress(OrderModelsAddress billingAddress) {
    this.billingAddress = billingAddress;
  }

  /**
   * List of order rows
   **/
  @ApiModelProperty(value = "List of order rows")
  public List<OrderModelsOrderRow> getRows() {
    return rows;
  }
  public void setRows(List<OrderModelsOrderRow> rows) {
    this.rows = rows;
  }

  /**
   * List of order refunds <seealso cref=\"T:Order.Models.Refund\" />.
   **/
  @ApiModelProperty(value = "List of order refunds <seealso cref=\"T:Order.Models.Refund\" />.")
  public List<OrderModelsRefund> getRefunds() {
    return refunds;
  }
  public void setRefunds(List<OrderModelsRefund> refunds) {
    this.refunds = refunds;
  }

  /**
   * Customer IP-number.
   **/
  @ApiModelProperty(value = "Customer IP-number.")
  public String getIp() {
    return ip;
  }
  public void setIp(String ip) {
    this.ip = ip;
  }

  /**
   * Customer User Agent.
   **/
  @ApiModelProperty(value = "Customer User Agent.")
  public String getUserAgent() {
    return userAgent;
  }
  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }

  /**
   * Chosen service location.
   **/
  @ApiModelProperty(value = "Chosen service location.")
  public String getServiceLocation() {
    return serviceLocation;
  }
  public void setServiceLocation(String serviceLocation) {
    this.serviceLocation = serviceLocation;
  }

  /**
   * Campaign code applied to the order.
   **/
  @ApiModelProperty(value = "Campaign code applied to the order.")
  public String getCampaignCode() {
    return campaignCode;
  }
  public void setCampaignCode(String campaignCode) {
    this.campaignCode = campaignCode;
  }

  /**
   * The internal id of the applied campaign code.
   **/
  @ApiModelProperty(value = "The internal id of the applied campaign code.")
  public Integer getCampaignCodeId() {
    return campaignCodeId;
  }
  public void setCampaignCodeId(Integer campaignCodeId) {
    this.campaignCodeId = campaignCodeId;
  }

  /**
   * General percent discount applied to the order.
   **/
  @ApiModelProperty(value = "General percent discount applied to the order.")
  public Integer getPercent() {
    return percent;
  }
  public void setPercent(Integer percent) {
    this.percent = percent;
  }

  /**
   * The desired delivery date of the order.
   **/
  @ApiModelProperty(value = "The desired delivery date of the order.")
  public Date getDesiredDeliveryDate() {
    return desiredDeliveryDate;
  }
  public void setDesiredDeliveryDate(Date desiredDeliveryDate) {
    this.desiredDeliveryDate = desiredDeliveryDate;
  }

  /**
   * The gender of the customer. True = male, False = female, null = unknown.
   **/
  @ApiModelProperty(value = "The gender of the customer. True = male, False = female, null = unknown.")
  public Boolean getGender() {
    return gender;
  }
  public void setGender(Boolean gender) {
    this.gender = gender;
  }

  /**
   * The unique identifier for the cart from which this order originates.
   **/
  @ApiModelProperty(value = "The unique identifier for the cart from which this order originates.")
  public Integer getCartId() {
    return cartId;
  }
  public void setCartId(Integer cartId) {
    this.cartId = cartId;
  }

  /**
   * The session id for the from which this order originates.
   **/
  @ApiModelProperty(value = "The session id for the from which this order originates.")
  public String getSessionId() {
    return sessionId;
  }
  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ExternalOrderStatusEnum getExternalOrderStatus() {
    return externalOrderStatus;
  }
  public void setExternalOrderStatus(ExternalOrderStatusEnum externalOrderStatus) {
    this.externalOrderStatus = externalOrderStatus;
  }

  /**
   * The ids for the campaigns applied to this order (not rows)
   **/
  @ApiModelProperty(value = "The ids for the campaigns applied to this order (not rows)")
  public List<String> getCampaignIds() {
    return campaignIds;
  }
  public void setCampaignIds(List<String> campaignIds) {
    this.campaignIds = campaignIds;
  }

  /**
   * The names for the campaigns applied to this order (not rows)
   **/
  @ApiModelProperty(value = "The names for the campaigns applied to this order (not rows)")
  public List<String> getCampaignNames() {
    return campaignNames;
  }
  public void setCampaignNames(List<String> campaignNames) {
    this.campaignNames = campaignNames;
  }

  /**
   * The order meta data to store additional information about the order. Eg. customer specific shipping data to include for nShift checkout (former UDC) shipments
   **/
  @ApiModelProperty(value = "The order meta data to store additional information about the order. Eg. customer specific shipping data to include for nShift checkout (former UDC) shipments")
  public Map<String, String> getMetaData() {
    return metaData;
  }
  public void setMetaData(Map<String, String> metaData) {
    this.metaData = metaData;
  }

  /**
   * The public id of this order.
   **/
  @ApiModelProperty(value = "The public id of this order.")
  public UUID getPublicId() {
    return publicId;
  }
  public void setPublicId(UUID publicId) {
    this.publicId = publicId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderModelsOrder orderModelsOrder = (OrderModelsOrder) o;
    return (this.id == null ? orderModelsOrder.id == null : this.id.equals(orderModelsOrder.id)) &&
        (this.externalId == null ? orderModelsOrder.externalId == null : this.externalId.equals(orderModelsOrder.externalId)) &&
        (this.personalId == null ? orderModelsOrder.personalId == null : this.personalId.equals(orderModelsOrder.personalId)) &&
        (this.customerId == null ? orderModelsOrder.customerId == null : this.customerId.equals(orderModelsOrder.customerId)) &&
        (this.customerTypeId == null ? orderModelsOrder.customerTypeId == null : this.customerTypeId.equals(orderModelsOrder.customerTypeId)) &&
        (this.createdAt == null ? orderModelsOrder.createdAt == null : this.createdAt.equals(orderModelsOrder.createdAt)) &&
        (this.updatedAt == null ? orderModelsOrder.updatedAt == null : this.updatedAt.equals(orderModelsOrder.updatedAt)) &&
        (this.completedAt == null ? orderModelsOrder.completedAt == null : this.completedAt.equals(orderModelsOrder.completedAt)) &&
        (this.status == null ? orderModelsOrder.status == null : this.status.equals(orderModelsOrder.status)) &&
        (this.currency == null ? orderModelsOrder.currency == null : this.currency.equals(orderModelsOrder.currency)) &&
        (this.currencyRate == null ? orderModelsOrder.currencyRate == null : this.currencyRate.equals(orderModelsOrder.currencyRate)) &&
        (this.marketId == null ? orderModelsOrder.marketId == null : this.marketId.equals(orderModelsOrder.marketId)) &&
        (this.marketName == null ? orderModelsOrder.marketName == null : this.marketName.equals(orderModelsOrder.marketName)) &&
        (this.language == null ? orderModelsOrder.language == null : this.language.equals(orderModelsOrder.language)) &&
        (this.orderTotal == null ? orderModelsOrder.orderTotal == null : this.orderTotal.equals(orderModelsOrder.orderTotal)) &&
        (this.expectedSum == null ? orderModelsOrder.expectedSum == null : this.expectedSum.equals(orderModelsOrder.expectedSum)) &&
        (this.vATTotal == null ? orderModelsOrder.vATTotal == null : this.vATTotal.equals(orderModelsOrder.vATTotal)) &&
        (this.orderValueIncVat == null ? orderModelsOrder.orderValueIncVat == null : this.orderValueIncVat.equals(orderModelsOrder.orderValueIncVat)) &&
        (this.orderValueExVat == null ? orderModelsOrder.orderValueExVat == null : this.orderValueExVat.equals(orderModelsOrder.orderValueExVat)) &&
        (this.itemValueIncVat == null ? orderModelsOrder.itemValueIncVat == null : this.itemValueIncVat.equals(orderModelsOrder.itemValueIncVat)) &&
        (this.itemValueExVat == null ? orderModelsOrder.itemValueExVat == null : this.itemValueExVat.equals(orderModelsOrder.itemValueExVat)) &&
        (this.discount == null ? orderModelsOrder.discount == null : this.discount.equals(orderModelsOrder.discount)) &&
        (this.discountExVat == null ? orderModelsOrder.discountExVat == null : this.discountExVat.equals(orderModelsOrder.discountExVat)) &&
        (this.fromBalance == null ? orderModelsOrder.fromBalance == null : this.fromBalance.equals(orderModelsOrder.fromBalance)) &&
        (this.shippingFee == null ? orderModelsOrder.shippingFee == null : this.shippingFee.equals(orderModelsOrder.shippingFee)) &&
        (this.shippingFeeExVat == null ? orderModelsOrder.shippingFeeExVat == null : this.shippingFeeExVat.equals(orderModelsOrder.shippingFeeExVat)) &&
        (this.paymentFee == null ? orderModelsOrder.paymentFee == null : this.paymentFee.equals(orderModelsOrder.paymentFee)) &&
        (this.paymentFeeExVat == null ? orderModelsOrder.paymentFeeExVat == null : this.paymentFeeExVat.equals(orderModelsOrder.paymentFeeExVat)) &&
        (this.message == null ? orderModelsOrder.message == null : this.message.equals(orderModelsOrder.message)) &&
        (this.orderMessages == null ? orderModelsOrder.orderMessages == null : this.orderMessages.equals(orderModelsOrder.orderMessages)) &&
        (this.paymentDetails == null ? orderModelsOrder.paymentDetails == null : this.paymentDetails.equals(orderModelsOrder.paymentDetails)) &&
        (this.shippingDetails == null ? orderModelsOrder.shippingDetails == null : this.shippingDetails.equals(orderModelsOrder.shippingDetails)) &&
        (this.shippingAddress == null ? orderModelsOrder.shippingAddress == null : this.shippingAddress.equals(orderModelsOrder.shippingAddress)) &&
        (this.billingAddress == null ? orderModelsOrder.billingAddress == null : this.billingAddress.equals(orderModelsOrder.billingAddress)) &&
        (this.rows == null ? orderModelsOrder.rows == null : this.rows.equals(orderModelsOrder.rows)) &&
        (this.refunds == null ? orderModelsOrder.refunds == null : this.refunds.equals(orderModelsOrder.refunds)) &&
        (this.ip == null ? orderModelsOrder.ip == null : this.ip.equals(orderModelsOrder.ip)) &&
        (this.userAgent == null ? orderModelsOrder.userAgent == null : this.userAgent.equals(orderModelsOrder.userAgent)) &&
        (this.serviceLocation == null ? orderModelsOrder.serviceLocation == null : this.serviceLocation.equals(orderModelsOrder.serviceLocation)) &&
        (this.campaignCode == null ? orderModelsOrder.campaignCode == null : this.campaignCode.equals(orderModelsOrder.campaignCode)) &&
        (this.campaignCodeId == null ? orderModelsOrder.campaignCodeId == null : this.campaignCodeId.equals(orderModelsOrder.campaignCodeId)) &&
        (this.percent == null ? orderModelsOrder.percent == null : this.percent.equals(orderModelsOrder.percent)) &&
        (this.desiredDeliveryDate == null ? orderModelsOrder.desiredDeliveryDate == null : this.desiredDeliveryDate.equals(orderModelsOrder.desiredDeliveryDate)) &&
        (this.gender == null ? orderModelsOrder.gender == null : this.gender.equals(orderModelsOrder.gender)) &&
        (this.cartId == null ? orderModelsOrder.cartId == null : this.cartId.equals(orderModelsOrder.cartId)) &&
        (this.sessionId == null ? orderModelsOrder.sessionId == null : this.sessionId.equals(orderModelsOrder.sessionId)) &&
        (this.externalOrderStatus == null ? orderModelsOrder.externalOrderStatus == null : this.externalOrderStatus.equals(orderModelsOrder.externalOrderStatus)) &&
        (this.campaignIds == null ? orderModelsOrder.campaignIds == null : this.campaignIds.equals(orderModelsOrder.campaignIds)) &&
        (this.campaignNames == null ? orderModelsOrder.campaignNames == null : this.campaignNames.equals(orderModelsOrder.campaignNames)) &&
        (this.metaData == null ? orderModelsOrder.metaData == null : this.metaData.equals(orderModelsOrder.metaData)) &&
        (this.publicId == null ? orderModelsOrder.publicId == null : this.publicId.equals(orderModelsOrder.publicId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.externalId == null ? 0: this.externalId.hashCode());
    result = 31 * result + (this.personalId == null ? 0: this.personalId.hashCode());
    result = 31 * result + (this.customerId == null ? 0: this.customerId.hashCode());
    result = 31 * result + (this.customerTypeId == null ? 0: this.customerTypeId.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.updatedAt == null ? 0: this.updatedAt.hashCode());
    result = 31 * result + (this.completedAt == null ? 0: this.completedAt.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.currencyRate == null ? 0: this.currencyRate.hashCode());
    result = 31 * result + (this.marketId == null ? 0: this.marketId.hashCode());
    result = 31 * result + (this.marketName == null ? 0: this.marketName.hashCode());
    result = 31 * result + (this.language == null ? 0: this.language.hashCode());
    result = 31 * result + (this.orderTotal == null ? 0: this.orderTotal.hashCode());
    result = 31 * result + (this.expectedSum == null ? 0: this.expectedSum.hashCode());
    result = 31 * result + (this.vATTotal == null ? 0: this.vATTotal.hashCode());
    result = 31 * result + (this.orderValueIncVat == null ? 0: this.orderValueIncVat.hashCode());
    result = 31 * result + (this.orderValueExVat == null ? 0: this.orderValueExVat.hashCode());
    result = 31 * result + (this.itemValueIncVat == null ? 0: this.itemValueIncVat.hashCode());
    result = 31 * result + (this.itemValueExVat == null ? 0: this.itemValueExVat.hashCode());
    result = 31 * result + (this.discount == null ? 0: this.discount.hashCode());
    result = 31 * result + (this.discountExVat == null ? 0: this.discountExVat.hashCode());
    result = 31 * result + (this.fromBalance == null ? 0: this.fromBalance.hashCode());
    result = 31 * result + (this.shippingFee == null ? 0: this.shippingFee.hashCode());
    result = 31 * result + (this.shippingFeeExVat == null ? 0: this.shippingFeeExVat.hashCode());
    result = 31 * result + (this.paymentFee == null ? 0: this.paymentFee.hashCode());
    result = 31 * result + (this.paymentFeeExVat == null ? 0: this.paymentFeeExVat.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.orderMessages == null ? 0: this.orderMessages.hashCode());
    result = 31 * result + (this.paymentDetails == null ? 0: this.paymentDetails.hashCode());
    result = 31 * result + (this.shippingDetails == null ? 0: this.shippingDetails.hashCode());
    result = 31 * result + (this.shippingAddress == null ? 0: this.shippingAddress.hashCode());
    result = 31 * result + (this.billingAddress == null ? 0: this.billingAddress.hashCode());
    result = 31 * result + (this.rows == null ? 0: this.rows.hashCode());
    result = 31 * result + (this.refunds == null ? 0: this.refunds.hashCode());
    result = 31 * result + (this.ip == null ? 0: this.ip.hashCode());
    result = 31 * result + (this.userAgent == null ? 0: this.userAgent.hashCode());
    result = 31 * result + (this.serviceLocation == null ? 0: this.serviceLocation.hashCode());
    result = 31 * result + (this.campaignCode == null ? 0: this.campaignCode.hashCode());
    result = 31 * result + (this.campaignCodeId == null ? 0: this.campaignCodeId.hashCode());
    result = 31 * result + (this.percent == null ? 0: this.percent.hashCode());
    result = 31 * result + (this.desiredDeliveryDate == null ? 0: this.desiredDeliveryDate.hashCode());
    result = 31 * result + (this.gender == null ? 0: this.gender.hashCode());
    result = 31 * result + (this.cartId == null ? 0: this.cartId.hashCode());
    result = 31 * result + (this.sessionId == null ? 0: this.sessionId.hashCode());
    result = 31 * result + (this.externalOrderStatus == null ? 0: this.externalOrderStatus.hashCode());
    result = 31 * result + (this.campaignIds == null ? 0: this.campaignIds.hashCode());
    result = 31 * result + (this.campaignNames == null ? 0: this.campaignNames.hashCode());
    result = 31 * result + (this.metaData == null ? 0: this.metaData.hashCode());
    result = 31 * result + (this.publicId == null ? 0: this.publicId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderModelsOrder {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  externalId: ").append(externalId).append("\n");
    sb.append("  personalId: ").append(personalId).append("\n");
    sb.append("  customerId: ").append(customerId).append("\n");
    sb.append("  customerTypeId: ").append(customerTypeId).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("  completedAt: ").append(completedAt).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  currencyRate: ").append(currencyRate).append("\n");
    sb.append("  marketId: ").append(marketId).append("\n");
    sb.append("  marketName: ").append(marketName).append("\n");
    sb.append("  language: ").append(language).append("\n");
    sb.append("  orderTotal: ").append(orderTotal).append("\n");
    sb.append("  expectedSum: ").append(expectedSum).append("\n");
    sb.append("  vATTotal: ").append(vATTotal).append("\n");
    sb.append("  orderValueIncVat: ").append(orderValueIncVat).append("\n");
    sb.append("  orderValueExVat: ").append(orderValueExVat).append("\n");
    sb.append("  itemValueIncVat: ").append(itemValueIncVat).append("\n");
    sb.append("  itemValueExVat: ").append(itemValueExVat).append("\n");
    sb.append("  discount: ").append(discount).append("\n");
    sb.append("  discountExVat: ").append(discountExVat).append("\n");
    sb.append("  fromBalance: ").append(fromBalance).append("\n");
    sb.append("  shippingFee: ").append(shippingFee).append("\n");
    sb.append("  shippingFeeExVat: ").append(shippingFeeExVat).append("\n");
    sb.append("  paymentFee: ").append(paymentFee).append("\n");
    sb.append("  paymentFeeExVat: ").append(paymentFeeExVat).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("  orderMessages: ").append(orderMessages).append("\n");
    sb.append("  paymentDetails: ").append(paymentDetails).append("\n");
    sb.append("  shippingDetails: ").append(shippingDetails).append("\n");
    sb.append("  shippingAddress: ").append(shippingAddress).append("\n");
    sb.append("  billingAddress: ").append(billingAddress).append("\n");
    sb.append("  rows: ").append(rows).append("\n");
    sb.append("  refunds: ").append(refunds).append("\n");
    sb.append("  ip: ").append(ip).append("\n");
    sb.append("  userAgent: ").append(userAgent).append("\n");
    sb.append("  serviceLocation: ").append(serviceLocation).append("\n");
    sb.append("  campaignCode: ").append(campaignCode).append("\n");
    sb.append("  campaignCodeId: ").append(campaignCodeId).append("\n");
    sb.append("  percent: ").append(percent).append("\n");
    sb.append("  desiredDeliveryDate: ").append(desiredDeliveryDate).append("\n");
    sb.append("  gender: ").append(gender).append("\n");
    sb.append("  cartId: ").append(cartId).append("\n");
    sb.append("  sessionId: ").append(sessionId).append("\n");
    sb.append("  externalOrderStatus: ").append(externalOrderStatus).append("\n");
    sb.append("  campaignIds: ").append(campaignIds).append("\n");
    sb.append("  campaignNames: ").append(campaignNames).append("\n");
    sb.append("  metaData: ").append(metaData).append("\n");
    sb.append("  publicId: ").append(publicId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
