/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderCheckoutOrderRow {
  
  @SerializedName("Sku")
  private String sku = null;
  @SerializedName("ProductId")
  private Integer productId = null;
  @SerializedName("ExternalId")
  private String externalId = null;
  @SerializedName("DiscountRate")
  private Double discountRate = null;
  @SerializedName("CartRowId")
  private Integer cartRowId = null;
  @SerializedName("ProductContainerBuildId")
  private Integer productContainerBuildId = null;
  @SerializedName("Message")
  private String message = null;
  @SerializedName("ArticleNumber")
  private String articleNumber = null;
  @SerializedName("Gtin")
  private String gtin = null;
  @SerializedName("Brand")
  private String brand = null;
  @SerializedName("Categories")
  private List<String> categories = null;
  @SerializedName("Name")
  private String name = null;
  @SerializedName("Variant")
  private String variant = null;
  @SerializedName("Quantity")
  private Integer quantity = null;
  @SerializedName("PriceIncVat")
  private Double priceIncVat = null;
  @SerializedName("PriceExVat")
  private Double priceExVat = null;
  @SerializedName("ExpectedTotalPriceIncVat")
  private Double expectedTotalPriceIncVat = null;
  @SerializedName("DiscountIncVat")
  private Double discountIncVat = null;
  @SerializedName("DiscountExVat")
  private Double discountExVat = null;
  @SerializedName("ExpectedTotalDiscountIncVat")
  private Double expectedTotalDiscountIncVat = null;
  @SerializedName("ProductUrl")
  private String productUrl = null;
  @SerializedName("ImageUrl")
  private String imageUrl = null;
  @SerializedName("Weight")
  private Integer weight = null;
  @SerializedName("Height")
  private Integer height = null;
  @SerializedName("Width")
  private Integer width = null;
  @SerializedName("Length")
  private Integer length = null;
  @SerializedName("CampaignIds")
  private List<String> campaignIds = null;
  @SerializedName("CampaignGroupData")
  private String campaignGroupData = null;
  @SerializedName("CampaignNames")
  private List<String> campaignNames = null;
  @SerializedName("ProductPriceCampaignId")
  private Integer productPriceCampaignId = null;
  @SerializedName("ProductPriceListId")
  private Integer productPriceListId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSku() {
    return sku;
  }
  public void setSku(String sku) {
    this.sku = sku;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getProductId() {
    return productId;
  }
  public void setProductId(Integer productId) {
    this.productId = productId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExternalId() {
    return externalId;
  }
  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getDiscountRate() {
    return discountRate;
  }
  public void setDiscountRate(Double discountRate) {
    this.discountRate = discountRate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCartRowId() {
    return cartRowId;
  }
  public void setCartRowId(Integer cartRowId) {
    this.cartRowId = cartRowId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getProductContainerBuildId() {
    return productContainerBuildId;
  }
  public void setProductContainerBuildId(Integer productContainerBuildId) {
    this.productContainerBuildId = productContainerBuildId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getArticleNumber() {
    return articleNumber;
  }
  public void setArticleNumber(String articleNumber) {
    this.articleNumber = articleNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGtin() {
    return gtin;
  }
  public void setGtin(String gtin) {
    this.gtin = gtin;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBrand() {
    return brand;
  }
  public void setBrand(String brand) {
    this.brand = brand;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getCategories() {
    return categories;
  }
  public void setCategories(List<String> categories) {
    this.categories = categories;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVariant() {
    return variant;
  }
  public void setVariant(String variant) {
    this.variant = variant;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getQuantity() {
    return quantity;
  }
  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getPriceIncVat() {
    return priceIncVat;
  }
  public void setPriceIncVat(Double priceIncVat) {
    this.priceIncVat = priceIncVat;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getPriceExVat() {
    return priceExVat;
  }
  public void setPriceExVat(Double priceExVat) {
    this.priceExVat = priceExVat;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getExpectedTotalPriceIncVat() {
    return expectedTotalPriceIncVat;
  }
  public void setExpectedTotalPriceIncVat(Double expectedTotalPriceIncVat) {
    this.expectedTotalPriceIncVat = expectedTotalPriceIncVat;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getDiscountIncVat() {
    return discountIncVat;
  }
  public void setDiscountIncVat(Double discountIncVat) {
    this.discountIncVat = discountIncVat;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getDiscountExVat() {
    return discountExVat;
  }
  public void setDiscountExVat(Double discountExVat) {
    this.discountExVat = discountExVat;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getExpectedTotalDiscountIncVat() {
    return expectedTotalDiscountIncVat;
  }
  public void setExpectedTotalDiscountIncVat(Double expectedTotalDiscountIncVat) {
    this.expectedTotalDiscountIncVat = expectedTotalDiscountIncVat;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductUrl() {
    return productUrl;
  }
  public void setProductUrl(String productUrl) {
    this.productUrl = productUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getImageUrl() {
    return imageUrl;
  }
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getWeight() {
    return weight;
  }
  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHeight() {
    return height;
  }
  public void setHeight(Integer height) {
    this.height = height;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getWidth() {
    return width;
  }
  public void setWidth(Integer width) {
    this.width = width;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getLength() {
    return length;
  }
  public void setLength(Integer length) {
    this.length = length;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getCampaignIds() {
    return campaignIds;
  }
  public void setCampaignIds(List<String> campaignIds) {
    this.campaignIds = campaignIds;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCampaignGroupData() {
    return campaignGroupData;
  }
  public void setCampaignGroupData(String campaignGroupData) {
    this.campaignGroupData = campaignGroupData;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getCampaignNames() {
    return campaignNames;
  }
  public void setCampaignNames(List<String> campaignNames) {
    this.campaignNames = campaignNames;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getProductPriceCampaignId() {
    return productPriceCampaignId;
  }
  public void setProductPriceCampaignId(Integer productPriceCampaignId) {
    this.productPriceCampaignId = productPriceCampaignId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getProductPriceListId() {
    return productPriceListId;
  }
  public void setProductPriceListId(Integer productPriceListId) {
    this.productPriceListId = productPriceListId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderCheckoutOrderRow orderCheckoutOrderRow = (OrderCheckoutOrderRow) o;
    return (this.sku == null ? orderCheckoutOrderRow.sku == null : this.sku.equals(orderCheckoutOrderRow.sku)) &&
        (this.productId == null ? orderCheckoutOrderRow.productId == null : this.productId.equals(orderCheckoutOrderRow.productId)) &&
        (this.externalId == null ? orderCheckoutOrderRow.externalId == null : this.externalId.equals(orderCheckoutOrderRow.externalId)) &&
        (this.discountRate == null ? orderCheckoutOrderRow.discountRate == null : this.discountRate.equals(orderCheckoutOrderRow.discountRate)) &&
        (this.cartRowId == null ? orderCheckoutOrderRow.cartRowId == null : this.cartRowId.equals(orderCheckoutOrderRow.cartRowId)) &&
        (this.productContainerBuildId == null ? orderCheckoutOrderRow.productContainerBuildId == null : this.productContainerBuildId.equals(orderCheckoutOrderRow.productContainerBuildId)) &&
        (this.message == null ? orderCheckoutOrderRow.message == null : this.message.equals(orderCheckoutOrderRow.message)) &&
        (this.articleNumber == null ? orderCheckoutOrderRow.articleNumber == null : this.articleNumber.equals(orderCheckoutOrderRow.articleNumber)) &&
        (this.gtin == null ? orderCheckoutOrderRow.gtin == null : this.gtin.equals(orderCheckoutOrderRow.gtin)) &&
        (this.brand == null ? orderCheckoutOrderRow.brand == null : this.brand.equals(orderCheckoutOrderRow.brand)) &&
        (this.categories == null ? orderCheckoutOrderRow.categories == null : this.categories.equals(orderCheckoutOrderRow.categories)) &&
        (this.name == null ? orderCheckoutOrderRow.name == null : this.name.equals(orderCheckoutOrderRow.name)) &&
        (this.variant == null ? orderCheckoutOrderRow.variant == null : this.variant.equals(orderCheckoutOrderRow.variant)) &&
        (this.quantity == null ? orderCheckoutOrderRow.quantity == null : this.quantity.equals(orderCheckoutOrderRow.quantity)) &&
        (this.priceIncVat == null ? orderCheckoutOrderRow.priceIncVat == null : this.priceIncVat.equals(orderCheckoutOrderRow.priceIncVat)) &&
        (this.priceExVat == null ? orderCheckoutOrderRow.priceExVat == null : this.priceExVat.equals(orderCheckoutOrderRow.priceExVat)) &&
        (this.expectedTotalPriceIncVat == null ? orderCheckoutOrderRow.expectedTotalPriceIncVat == null : this.expectedTotalPriceIncVat.equals(orderCheckoutOrderRow.expectedTotalPriceIncVat)) &&
        (this.discountIncVat == null ? orderCheckoutOrderRow.discountIncVat == null : this.discountIncVat.equals(orderCheckoutOrderRow.discountIncVat)) &&
        (this.discountExVat == null ? orderCheckoutOrderRow.discountExVat == null : this.discountExVat.equals(orderCheckoutOrderRow.discountExVat)) &&
        (this.expectedTotalDiscountIncVat == null ? orderCheckoutOrderRow.expectedTotalDiscountIncVat == null : this.expectedTotalDiscountIncVat.equals(orderCheckoutOrderRow.expectedTotalDiscountIncVat)) &&
        (this.productUrl == null ? orderCheckoutOrderRow.productUrl == null : this.productUrl.equals(orderCheckoutOrderRow.productUrl)) &&
        (this.imageUrl == null ? orderCheckoutOrderRow.imageUrl == null : this.imageUrl.equals(orderCheckoutOrderRow.imageUrl)) &&
        (this.weight == null ? orderCheckoutOrderRow.weight == null : this.weight.equals(orderCheckoutOrderRow.weight)) &&
        (this.height == null ? orderCheckoutOrderRow.height == null : this.height.equals(orderCheckoutOrderRow.height)) &&
        (this.width == null ? orderCheckoutOrderRow.width == null : this.width.equals(orderCheckoutOrderRow.width)) &&
        (this.length == null ? orderCheckoutOrderRow.length == null : this.length.equals(orderCheckoutOrderRow.length)) &&
        (this.campaignIds == null ? orderCheckoutOrderRow.campaignIds == null : this.campaignIds.equals(orderCheckoutOrderRow.campaignIds)) &&
        (this.campaignGroupData == null ? orderCheckoutOrderRow.campaignGroupData == null : this.campaignGroupData.equals(orderCheckoutOrderRow.campaignGroupData)) &&
        (this.campaignNames == null ? orderCheckoutOrderRow.campaignNames == null : this.campaignNames.equals(orderCheckoutOrderRow.campaignNames)) &&
        (this.productPriceCampaignId == null ? orderCheckoutOrderRow.productPriceCampaignId == null : this.productPriceCampaignId.equals(orderCheckoutOrderRow.productPriceCampaignId)) &&
        (this.productPriceListId == null ? orderCheckoutOrderRow.productPriceListId == null : this.productPriceListId.equals(orderCheckoutOrderRow.productPriceListId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sku == null ? 0: this.sku.hashCode());
    result = 31 * result + (this.productId == null ? 0: this.productId.hashCode());
    result = 31 * result + (this.externalId == null ? 0: this.externalId.hashCode());
    result = 31 * result + (this.discountRate == null ? 0: this.discountRate.hashCode());
    result = 31 * result + (this.cartRowId == null ? 0: this.cartRowId.hashCode());
    result = 31 * result + (this.productContainerBuildId == null ? 0: this.productContainerBuildId.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.articleNumber == null ? 0: this.articleNumber.hashCode());
    result = 31 * result + (this.gtin == null ? 0: this.gtin.hashCode());
    result = 31 * result + (this.brand == null ? 0: this.brand.hashCode());
    result = 31 * result + (this.categories == null ? 0: this.categories.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.variant == null ? 0: this.variant.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    result = 31 * result + (this.priceIncVat == null ? 0: this.priceIncVat.hashCode());
    result = 31 * result + (this.priceExVat == null ? 0: this.priceExVat.hashCode());
    result = 31 * result + (this.expectedTotalPriceIncVat == null ? 0: this.expectedTotalPriceIncVat.hashCode());
    result = 31 * result + (this.discountIncVat == null ? 0: this.discountIncVat.hashCode());
    result = 31 * result + (this.discountExVat == null ? 0: this.discountExVat.hashCode());
    result = 31 * result + (this.expectedTotalDiscountIncVat == null ? 0: this.expectedTotalDiscountIncVat.hashCode());
    result = 31 * result + (this.productUrl == null ? 0: this.productUrl.hashCode());
    result = 31 * result + (this.imageUrl == null ? 0: this.imageUrl.hashCode());
    result = 31 * result + (this.weight == null ? 0: this.weight.hashCode());
    result = 31 * result + (this.height == null ? 0: this.height.hashCode());
    result = 31 * result + (this.width == null ? 0: this.width.hashCode());
    result = 31 * result + (this.length == null ? 0: this.length.hashCode());
    result = 31 * result + (this.campaignIds == null ? 0: this.campaignIds.hashCode());
    result = 31 * result + (this.campaignGroupData == null ? 0: this.campaignGroupData.hashCode());
    result = 31 * result + (this.campaignNames == null ? 0: this.campaignNames.hashCode());
    result = 31 * result + (this.productPriceCampaignId == null ? 0: this.productPriceCampaignId.hashCode());
    result = 31 * result + (this.productPriceListId == null ? 0: this.productPriceListId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderCheckoutOrderRow {\n");
    
    sb.append("  sku: ").append(sku).append("\n");
    sb.append("  productId: ").append(productId).append("\n");
    sb.append("  externalId: ").append(externalId).append("\n");
    sb.append("  discountRate: ").append(discountRate).append("\n");
    sb.append("  cartRowId: ").append(cartRowId).append("\n");
    sb.append("  productContainerBuildId: ").append(productContainerBuildId).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("  articleNumber: ").append(articleNumber).append("\n");
    sb.append("  gtin: ").append(gtin).append("\n");
    sb.append("  brand: ").append(brand).append("\n");
    sb.append("  categories: ").append(categories).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  variant: ").append(variant).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("  priceIncVat: ").append(priceIncVat).append("\n");
    sb.append("  priceExVat: ").append(priceExVat).append("\n");
    sb.append("  expectedTotalPriceIncVat: ").append(expectedTotalPriceIncVat).append("\n");
    sb.append("  discountIncVat: ").append(discountIncVat).append("\n");
    sb.append("  discountExVat: ").append(discountExVat).append("\n");
    sb.append("  expectedTotalDiscountIncVat: ").append(expectedTotalDiscountIncVat).append("\n");
    sb.append("  productUrl: ").append(productUrl).append("\n");
    sb.append("  imageUrl: ").append(imageUrl).append("\n");
    sb.append("  weight: ").append(weight).append("\n");
    sb.append("  height: ").append(height).append("\n");
    sb.append("  width: ").append(width).append("\n");
    sb.append("  length: ").append(length).append("\n");
    sb.append("  campaignIds: ").append(campaignIds).append("\n");
    sb.append("  campaignGroupData: ").append(campaignGroupData).append("\n");
    sb.append("  campaignNames: ").append(campaignNames).append("\n");
    sb.append("  productPriceCampaignId: ").append(productPriceCampaignId).append("\n");
    sb.append("  productPriceListId: ").append(productPriceListId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
