/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Date;
import java.util.UUID;
import org.openapitools.client.model.OrderCaptureRow;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderCapture {
  
  @SerializedName("CaptureId")
  private UUID captureId = null;
  @SerializedName("OrderPaymentId")
  private UUID orderPaymentId = null;
  @SerializedName("OrderId")
  private Integer orderId = null;
  @SerializedName("ExternalOrderId")
  private String externalOrderId = null;
  @SerializedName("ExternalId")
  private String externalId = null;
  @SerializedName("Reference")
  private String reference = null;
  @SerializedName("Description")
  private String description = null;
  @SerializedName("ProcessedOn")
  private Date processedOn = null;
  @SerializedName("CapturedItemTotal")
  private Double capturedItemTotal = null;
  @SerializedName("CapturedShippingFee")
  private Double capturedShippingFee = null;
  @SerializedName("CapturedPaymentFee")
  private Double capturedPaymentFee = null;
  @SerializedName("CapturedDiscount")
  private Double capturedDiscount = null;
  @SerializedName("CapturedBalance")
  private Double capturedBalance = null;
  @SerializedName("VatRate")
  private Double vatRate = null;
  @SerializedName("TrackingNumber")
  private String trackingNumber = null;
  @SerializedName("ShippingName")
  private String shippingName = null;
  @SerializedName("TrackingUri")
  private String trackingUri = null;
  @SerializedName("ShippingMethod")
  private String shippingMethod = null;
  @SerializedName("PaymentName")
  private String paymentName = null;
  @SerializedName("Locale")
  private String locale = null;
  @SerializedName("Rows")
  private List<OrderCaptureRow> rows = null;
  @SerializedName("OrderTransactionId")
  private String orderTransactionId = null;
  @SerializedName("SecondaryOrderTransactionId")
  private String secondaryOrderTransactionId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getCaptureId() {
    return captureId;
  }
  public void setCaptureId(UUID captureId) {
    this.captureId = captureId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getOrderPaymentId() {
    return orderPaymentId;
  }
  public void setOrderPaymentId(UUID orderPaymentId) {
    this.orderPaymentId = orderPaymentId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOrderId() {
    return orderId;
  }
  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExternalOrderId() {
    return externalOrderId;
  }
  public void setExternalOrderId(String externalOrderId) {
    this.externalOrderId = externalOrderId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExternalId() {
    return externalId;
  }
  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getReference() {
    return reference;
  }
  public void setReference(String reference) {
    this.reference = reference;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getProcessedOn() {
    return processedOn;
  }
  public void setProcessedOn(Date processedOn) {
    this.processedOn = processedOn;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getCapturedItemTotal() {
    return capturedItemTotal;
  }
  public void setCapturedItemTotal(Double capturedItemTotal) {
    this.capturedItemTotal = capturedItemTotal;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getCapturedShippingFee() {
    return capturedShippingFee;
  }
  public void setCapturedShippingFee(Double capturedShippingFee) {
    this.capturedShippingFee = capturedShippingFee;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getCapturedPaymentFee() {
    return capturedPaymentFee;
  }
  public void setCapturedPaymentFee(Double capturedPaymentFee) {
    this.capturedPaymentFee = capturedPaymentFee;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getCapturedDiscount() {
    return capturedDiscount;
  }
  public void setCapturedDiscount(Double capturedDiscount) {
    this.capturedDiscount = capturedDiscount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getCapturedBalance() {
    return capturedBalance;
  }
  public void setCapturedBalance(Double capturedBalance) {
    this.capturedBalance = capturedBalance;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getVatRate() {
    return vatRate;
  }
  public void setVatRate(Double vatRate) {
    this.vatRate = vatRate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTrackingNumber() {
    return trackingNumber;
  }
  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getShippingName() {
    return shippingName;
  }
  public void setShippingName(String shippingName) {
    this.shippingName = shippingName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTrackingUri() {
    return trackingUri;
  }
  public void setTrackingUri(String trackingUri) {
    this.trackingUri = trackingUri;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getShippingMethod() {
    return shippingMethod;
  }
  public void setShippingMethod(String shippingMethod) {
    this.shippingMethod = shippingMethod;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPaymentName() {
    return paymentName;
  }
  public void setPaymentName(String paymentName) {
    this.paymentName = paymentName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLocale() {
    return locale;
  }
  public void setLocale(String locale) {
    this.locale = locale;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<OrderCaptureRow> getRows() {
    return rows;
  }
  public void setRows(List<OrderCaptureRow> rows) {
    this.rows = rows;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrderTransactionId() {
    return orderTransactionId;
  }
  public void setOrderTransactionId(String orderTransactionId) {
    this.orderTransactionId = orderTransactionId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSecondaryOrderTransactionId() {
    return secondaryOrderTransactionId;
  }
  public void setSecondaryOrderTransactionId(String secondaryOrderTransactionId) {
    this.secondaryOrderTransactionId = secondaryOrderTransactionId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderCapture orderCapture = (OrderCapture) o;
    return (this.captureId == null ? orderCapture.captureId == null : this.captureId.equals(orderCapture.captureId)) &&
        (this.orderPaymentId == null ? orderCapture.orderPaymentId == null : this.orderPaymentId.equals(orderCapture.orderPaymentId)) &&
        (this.orderId == null ? orderCapture.orderId == null : this.orderId.equals(orderCapture.orderId)) &&
        (this.externalOrderId == null ? orderCapture.externalOrderId == null : this.externalOrderId.equals(orderCapture.externalOrderId)) &&
        (this.externalId == null ? orderCapture.externalId == null : this.externalId.equals(orderCapture.externalId)) &&
        (this.reference == null ? orderCapture.reference == null : this.reference.equals(orderCapture.reference)) &&
        (this.description == null ? orderCapture.description == null : this.description.equals(orderCapture.description)) &&
        (this.processedOn == null ? orderCapture.processedOn == null : this.processedOn.equals(orderCapture.processedOn)) &&
        (this.capturedItemTotal == null ? orderCapture.capturedItemTotal == null : this.capturedItemTotal.equals(orderCapture.capturedItemTotal)) &&
        (this.capturedShippingFee == null ? orderCapture.capturedShippingFee == null : this.capturedShippingFee.equals(orderCapture.capturedShippingFee)) &&
        (this.capturedPaymentFee == null ? orderCapture.capturedPaymentFee == null : this.capturedPaymentFee.equals(orderCapture.capturedPaymentFee)) &&
        (this.capturedDiscount == null ? orderCapture.capturedDiscount == null : this.capturedDiscount.equals(orderCapture.capturedDiscount)) &&
        (this.capturedBalance == null ? orderCapture.capturedBalance == null : this.capturedBalance.equals(orderCapture.capturedBalance)) &&
        (this.vatRate == null ? orderCapture.vatRate == null : this.vatRate.equals(orderCapture.vatRate)) &&
        (this.trackingNumber == null ? orderCapture.trackingNumber == null : this.trackingNumber.equals(orderCapture.trackingNumber)) &&
        (this.shippingName == null ? orderCapture.shippingName == null : this.shippingName.equals(orderCapture.shippingName)) &&
        (this.trackingUri == null ? orderCapture.trackingUri == null : this.trackingUri.equals(orderCapture.trackingUri)) &&
        (this.shippingMethod == null ? orderCapture.shippingMethod == null : this.shippingMethod.equals(orderCapture.shippingMethod)) &&
        (this.paymentName == null ? orderCapture.paymentName == null : this.paymentName.equals(orderCapture.paymentName)) &&
        (this.locale == null ? orderCapture.locale == null : this.locale.equals(orderCapture.locale)) &&
        (this.rows == null ? orderCapture.rows == null : this.rows.equals(orderCapture.rows)) &&
        (this.orderTransactionId == null ? orderCapture.orderTransactionId == null : this.orderTransactionId.equals(orderCapture.orderTransactionId)) &&
        (this.secondaryOrderTransactionId == null ? orderCapture.secondaryOrderTransactionId == null : this.secondaryOrderTransactionId.equals(orderCapture.secondaryOrderTransactionId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.captureId == null ? 0: this.captureId.hashCode());
    result = 31 * result + (this.orderPaymentId == null ? 0: this.orderPaymentId.hashCode());
    result = 31 * result + (this.orderId == null ? 0: this.orderId.hashCode());
    result = 31 * result + (this.externalOrderId == null ? 0: this.externalOrderId.hashCode());
    result = 31 * result + (this.externalId == null ? 0: this.externalId.hashCode());
    result = 31 * result + (this.reference == null ? 0: this.reference.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.processedOn == null ? 0: this.processedOn.hashCode());
    result = 31 * result + (this.capturedItemTotal == null ? 0: this.capturedItemTotal.hashCode());
    result = 31 * result + (this.capturedShippingFee == null ? 0: this.capturedShippingFee.hashCode());
    result = 31 * result + (this.capturedPaymentFee == null ? 0: this.capturedPaymentFee.hashCode());
    result = 31 * result + (this.capturedDiscount == null ? 0: this.capturedDiscount.hashCode());
    result = 31 * result + (this.capturedBalance == null ? 0: this.capturedBalance.hashCode());
    result = 31 * result + (this.vatRate == null ? 0: this.vatRate.hashCode());
    result = 31 * result + (this.trackingNumber == null ? 0: this.trackingNumber.hashCode());
    result = 31 * result + (this.shippingName == null ? 0: this.shippingName.hashCode());
    result = 31 * result + (this.trackingUri == null ? 0: this.trackingUri.hashCode());
    result = 31 * result + (this.shippingMethod == null ? 0: this.shippingMethod.hashCode());
    result = 31 * result + (this.paymentName == null ? 0: this.paymentName.hashCode());
    result = 31 * result + (this.locale == null ? 0: this.locale.hashCode());
    result = 31 * result + (this.rows == null ? 0: this.rows.hashCode());
    result = 31 * result + (this.orderTransactionId == null ? 0: this.orderTransactionId.hashCode());
    result = 31 * result + (this.secondaryOrderTransactionId == null ? 0: this.secondaryOrderTransactionId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderCapture {\n");
    
    sb.append("  captureId: ").append(captureId).append("\n");
    sb.append("  orderPaymentId: ").append(orderPaymentId).append("\n");
    sb.append("  orderId: ").append(orderId).append("\n");
    sb.append("  externalOrderId: ").append(externalOrderId).append("\n");
    sb.append("  externalId: ").append(externalId).append("\n");
    sb.append("  reference: ").append(reference).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  processedOn: ").append(processedOn).append("\n");
    sb.append("  capturedItemTotal: ").append(capturedItemTotal).append("\n");
    sb.append("  capturedShippingFee: ").append(capturedShippingFee).append("\n");
    sb.append("  capturedPaymentFee: ").append(capturedPaymentFee).append("\n");
    sb.append("  capturedDiscount: ").append(capturedDiscount).append("\n");
    sb.append("  capturedBalance: ").append(capturedBalance).append("\n");
    sb.append("  vatRate: ").append(vatRate).append("\n");
    sb.append("  trackingNumber: ").append(trackingNumber).append("\n");
    sb.append("  shippingName: ").append(shippingName).append("\n");
    sb.append("  trackingUri: ").append(trackingUri).append("\n");
    sb.append("  shippingMethod: ").append(shippingMethod).append("\n");
    sb.append("  paymentName: ").append(paymentName).append("\n");
    sb.append("  locale: ").append(locale).append("\n");
    sb.append("  rows: ").append(rows).append("\n");
    sb.append("  orderTransactionId: ").append(orderTransactionId).append("\n");
    sb.append("  secondaryOrderTransactionId: ").append(secondaryOrderTransactionId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
