/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PaymentModelsPaymentOption {
  
  @SerializedName("PaymentId")
  private Integer paymentId = null;
  @SerializedName("PaymentGroupId")
  private Integer paymentGroupId = null;
  @SerializedName("Name")
  private String name = null;
  @SerializedName("DisplayName")
  private String displayName = null;
  @SerializedName("Fee")
  private Double fee = null;
  @SerializedName("Icon")
  private String icon = null;
  @SerializedName("Sort")
  private Integer sort = null;
  @SerializedName("Period")
  private Integer period = null;
  @SerializedName("TermsLink")
  private String termsLink = null;
  @SerializedName("InfoLink")
  private String infoLink = null;
  @SerializedName("PersonalIdRequired")
  private Boolean personalIdRequired = null;
  @SerializedName("RegisteredAddressRequired")
  private Boolean registeredAddressRequired = null;
  @SerializedName("HouseNumberRequired")
  private Boolean houseNumberRequired = null;
  @SerializedName("HouseExtensionShown")
  private Boolean houseExtensionShown = null;
  @SerializedName("GenderRequired")
  private Boolean genderRequired = null;
  @SerializedName("BirthdateRequired")
  private Boolean birthdateRequired = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPaymentId() {
    return paymentId;
  }
  public void setPaymentId(Integer paymentId) {
    this.paymentId = paymentId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPaymentGroupId() {
    return paymentGroupId;
  }
  public void setPaymentGroupId(Integer paymentGroupId) {
    this.paymentGroupId = paymentGroupId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getFee() {
    return fee;
  }
  public void setFee(Double fee) {
    this.fee = fee;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIcon() {
    return icon;
  }
  public void setIcon(String icon) {
    this.icon = icon;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSort() {
    return sort;
  }
  public void setSort(Integer sort) {
    this.sort = sort;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPeriod() {
    return period;
  }
  public void setPeriod(Integer period) {
    this.period = period;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTermsLink() {
    return termsLink;
  }
  public void setTermsLink(String termsLink) {
    this.termsLink = termsLink;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInfoLink() {
    return infoLink;
  }
  public void setInfoLink(String infoLink) {
    this.infoLink = infoLink;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getPersonalIdRequired() {
    return personalIdRequired;
  }
  public void setPersonalIdRequired(Boolean personalIdRequired) {
    this.personalIdRequired = personalIdRequired;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getRegisteredAddressRequired() {
    return registeredAddressRequired;
  }
  public void setRegisteredAddressRequired(Boolean registeredAddressRequired) {
    this.registeredAddressRequired = registeredAddressRequired;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getHouseNumberRequired() {
    return houseNumberRequired;
  }
  public void setHouseNumberRequired(Boolean houseNumberRequired) {
    this.houseNumberRequired = houseNumberRequired;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getHouseExtensionShown() {
    return houseExtensionShown;
  }
  public void setHouseExtensionShown(Boolean houseExtensionShown) {
    this.houseExtensionShown = houseExtensionShown;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getGenderRequired() {
    return genderRequired;
  }
  public void setGenderRequired(Boolean genderRequired) {
    this.genderRequired = genderRequired;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getBirthdateRequired() {
    return birthdateRequired;
  }
  public void setBirthdateRequired(Boolean birthdateRequired) {
    this.birthdateRequired = birthdateRequired;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentModelsPaymentOption paymentModelsPaymentOption = (PaymentModelsPaymentOption) o;
    return (this.paymentId == null ? paymentModelsPaymentOption.paymentId == null : this.paymentId.equals(paymentModelsPaymentOption.paymentId)) &&
        (this.paymentGroupId == null ? paymentModelsPaymentOption.paymentGroupId == null : this.paymentGroupId.equals(paymentModelsPaymentOption.paymentGroupId)) &&
        (this.name == null ? paymentModelsPaymentOption.name == null : this.name.equals(paymentModelsPaymentOption.name)) &&
        (this.displayName == null ? paymentModelsPaymentOption.displayName == null : this.displayName.equals(paymentModelsPaymentOption.displayName)) &&
        (this.fee == null ? paymentModelsPaymentOption.fee == null : this.fee.equals(paymentModelsPaymentOption.fee)) &&
        (this.icon == null ? paymentModelsPaymentOption.icon == null : this.icon.equals(paymentModelsPaymentOption.icon)) &&
        (this.sort == null ? paymentModelsPaymentOption.sort == null : this.sort.equals(paymentModelsPaymentOption.sort)) &&
        (this.period == null ? paymentModelsPaymentOption.period == null : this.period.equals(paymentModelsPaymentOption.period)) &&
        (this.termsLink == null ? paymentModelsPaymentOption.termsLink == null : this.termsLink.equals(paymentModelsPaymentOption.termsLink)) &&
        (this.infoLink == null ? paymentModelsPaymentOption.infoLink == null : this.infoLink.equals(paymentModelsPaymentOption.infoLink)) &&
        (this.personalIdRequired == null ? paymentModelsPaymentOption.personalIdRequired == null : this.personalIdRequired.equals(paymentModelsPaymentOption.personalIdRequired)) &&
        (this.registeredAddressRequired == null ? paymentModelsPaymentOption.registeredAddressRequired == null : this.registeredAddressRequired.equals(paymentModelsPaymentOption.registeredAddressRequired)) &&
        (this.houseNumberRequired == null ? paymentModelsPaymentOption.houseNumberRequired == null : this.houseNumberRequired.equals(paymentModelsPaymentOption.houseNumberRequired)) &&
        (this.houseExtensionShown == null ? paymentModelsPaymentOption.houseExtensionShown == null : this.houseExtensionShown.equals(paymentModelsPaymentOption.houseExtensionShown)) &&
        (this.genderRequired == null ? paymentModelsPaymentOption.genderRequired == null : this.genderRequired.equals(paymentModelsPaymentOption.genderRequired)) &&
        (this.birthdateRequired == null ? paymentModelsPaymentOption.birthdateRequired == null : this.birthdateRequired.equals(paymentModelsPaymentOption.birthdateRequired));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.paymentId == null ? 0: this.paymentId.hashCode());
    result = 31 * result + (this.paymentGroupId == null ? 0: this.paymentGroupId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.fee == null ? 0: this.fee.hashCode());
    result = 31 * result + (this.icon == null ? 0: this.icon.hashCode());
    result = 31 * result + (this.sort == null ? 0: this.sort.hashCode());
    result = 31 * result + (this.period == null ? 0: this.period.hashCode());
    result = 31 * result + (this.termsLink == null ? 0: this.termsLink.hashCode());
    result = 31 * result + (this.infoLink == null ? 0: this.infoLink.hashCode());
    result = 31 * result + (this.personalIdRequired == null ? 0: this.personalIdRequired.hashCode());
    result = 31 * result + (this.registeredAddressRequired == null ? 0: this.registeredAddressRequired.hashCode());
    result = 31 * result + (this.houseNumberRequired == null ? 0: this.houseNumberRequired.hashCode());
    result = 31 * result + (this.houseExtensionShown == null ? 0: this.houseExtensionShown.hashCode());
    result = 31 * result + (this.genderRequired == null ? 0: this.genderRequired.hashCode());
    result = 31 * result + (this.birthdateRequired == null ? 0: this.birthdateRequired.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentModelsPaymentOption {\n");
    
    sb.append("  paymentId: ").append(paymentId).append("\n");
    sb.append("  paymentGroupId: ").append(paymentGroupId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  fee: ").append(fee).append("\n");
    sb.append("  icon: ").append(icon).append("\n");
    sb.append("  sort: ").append(sort).append("\n");
    sb.append("  period: ").append(period).append("\n");
    sb.append("  termsLink: ").append(termsLink).append("\n");
    sb.append("  infoLink: ").append(infoLink).append("\n");
    sb.append("  personalIdRequired: ").append(personalIdRequired).append("\n");
    sb.append("  registeredAddressRequired: ").append(registeredAddressRequired).append("\n");
    sb.append("  houseNumberRequired: ").append(houseNumberRequired).append("\n");
    sb.append("  houseExtensionShown: ").append(houseExtensionShown).append("\n");
    sb.append("  genderRequired: ").append(genderRequired).append("\n");
    sb.append("  birthdateRequired: ").append(birthdateRequired).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
