/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PaymentModelsPaymentOptionQuery {
  
  @SerializedName("SiteId")
  private Integer siteId = null;
  @SerializedName("Email")
  private String email = null;
  @SerializedName("CustomerTypeId")
  private Integer customerTypeId = null;
  @SerializedName("CountryId")
  private Integer countryId = null;
  @SerializedName("Sum")
  private Double sum = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSiteId() {
    return siteId;
  }
  public void setSiteId(Integer siteId) {
    this.siteId = siteId;
  }

  /**
   * Customer email address
   **/
  @ApiModelProperty(value = "Customer email address")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCustomerTypeId() {
    return customerTypeId;
  }
  public void setCustomerTypeId(Integer customerTypeId) {
    this.customerTypeId = customerTypeId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCountryId() {
    return countryId;
  }
  public void setCountryId(Integer countryId) {
    this.countryId = countryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getSum() {
    return sum;
  }
  public void setSum(Double sum) {
    this.sum = sum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentModelsPaymentOptionQuery paymentModelsPaymentOptionQuery = (PaymentModelsPaymentOptionQuery) o;
    return (this.siteId == null ? paymentModelsPaymentOptionQuery.siteId == null : this.siteId.equals(paymentModelsPaymentOptionQuery.siteId)) &&
        (this.email == null ? paymentModelsPaymentOptionQuery.email == null : this.email.equals(paymentModelsPaymentOptionQuery.email)) &&
        (this.customerTypeId == null ? paymentModelsPaymentOptionQuery.customerTypeId == null : this.customerTypeId.equals(paymentModelsPaymentOptionQuery.customerTypeId)) &&
        (this.countryId == null ? paymentModelsPaymentOptionQuery.countryId == null : this.countryId.equals(paymentModelsPaymentOptionQuery.countryId)) &&
        (this.sum == null ? paymentModelsPaymentOptionQuery.sum == null : this.sum.equals(paymentModelsPaymentOptionQuery.sum));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.siteId == null ? 0: this.siteId.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.customerTypeId == null ? 0: this.customerTypeId.hashCode());
    result = 31 * result + (this.countryId == null ? 0: this.countryId.hashCode());
    result = 31 * result + (this.sum == null ? 0: this.sum.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentModelsPaymentOptionQuery {\n");
    
    sb.append("  siteId: ").append(siteId).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  customerTypeId: ").append(customerTypeId).append("\n");
    sb.append("  countryId: ").append(countryId).append("\n");
    sb.append("  sum: ").append(sum).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
