/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A price for a product on a specific price list.
 **/
@ApiModel(description = "A price for a product on a specific price list.")
public class PriceListModelsReadPriceListPrice {
  
  @SerializedName("ProductId")
  private Integer productId = null;
  @SerializedName("PriceListId")
  private Integer priceListId = null;
  @SerializedName("PriceListName")
  private String priceListName = null;
  @SerializedName("PriceIncVat")
  private Double priceIncVat = null;
  @SerializedName("PriceExVat")
  private Double priceExVat = null;
  @SerializedName("VatRate")
  private Double vatRate = null;
  @SerializedName("Country")
  private String country = null;
  @SerializedName("Currency")
  private String currency = null;
  @SerializedName("StaggeredCount")
  private Integer staggeredCount = null;
  @SerializedName("ValidFrom")
  private Date validFrom = null;
  @SerializedName("ValidTo")
  private Date validTo = null;

  /**
   * The id of the product that this price applies to.
   **/
  @ApiModelProperty(value = "The id of the product that this price applies to.")
  public Integer getProductId() {
    return productId;
  }
  public void setProductId(Integer productId) {
    this.productId = productId;
  }

  /**
   * The id of the price list that this price is associated with.
   **/
  @ApiModelProperty(value = "The id of the price list that this price is associated with.")
  public Integer getPriceListId() {
    return priceListId;
  }
  public void setPriceListId(Integer priceListId) {
    this.priceListId = priceListId;
  }

  /**
   * The name of the price list that this price is associated with.
   **/
  @ApiModelProperty(value = "The name of the price list that this price is associated with.")
  public String getPriceListName() {
    return priceListName;
  }
  public void setPriceListName(String priceListName) {
    this.priceListName = priceListName;
  }

  /**
   * The price, inc VAT, in the currency of the associated price list.
   **/
  @ApiModelProperty(value = "The price, inc VAT, in the currency of the associated price list.")
  public Double getPriceIncVat() {
    return priceIncVat;
  }
  public void setPriceIncVat(Double priceIncVat) {
    this.priceIncVat = priceIncVat;
  }

  /**
   * The price, ex VAT, in the currency of the associated price list.
   **/
  @ApiModelProperty(value = "The price, ex VAT, in the currency of the associated price list.")
  public Double getPriceExVat() {
    return priceExVat;
  }
  public void setPriceExVat(Double priceExVat) {
    this.priceExVat = priceExVat;
  }

  /**
   * The Vat Rate
   **/
  @ApiModelProperty(value = "The Vat Rate")
  public Double getVatRate() {
    return vatRate;
  }
  public void setVatRate(Double vatRate) {
    this.vatRate = vatRate;
  }

  /**
   * The 2-letter ISO country code for this price.
   **/
  @ApiModelProperty(value = "The 2-letter ISO country code for this price.")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   * The 3-letter ISO 4217 currency code for this price.
   **/
  @ApiModelProperty(value = "The 3-letter ISO 4217 currency code for this price.")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }

  /**
   * Staggered count for this price. Defaults to 1.
   **/
  @ApiModelProperty(value = "Staggered count for this price. Defaults to 1.")
  public Integer getStaggeredCount() {
    return staggeredCount;
  }
  public void setStaggeredCount(Integer staggeredCount) {
    this.staggeredCount = staggeredCount;
  }

  /**
   * The date the price is valid from.
   **/
  @ApiModelProperty(value = "The date the price is valid from.")
  public Date getValidFrom() {
    return validFrom;
  }
  public void setValidFrom(Date validFrom) {
    this.validFrom = validFrom;
  }

  /**
   * The date the price is valid to.
   **/
  @ApiModelProperty(value = "The date the price is valid to.")
  public Date getValidTo() {
    return validTo;
  }
  public void setValidTo(Date validTo) {
    this.validTo = validTo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceListModelsReadPriceListPrice priceListModelsReadPriceListPrice = (PriceListModelsReadPriceListPrice) o;
    return (this.productId == null ? priceListModelsReadPriceListPrice.productId == null : this.productId.equals(priceListModelsReadPriceListPrice.productId)) &&
        (this.priceListId == null ? priceListModelsReadPriceListPrice.priceListId == null : this.priceListId.equals(priceListModelsReadPriceListPrice.priceListId)) &&
        (this.priceListName == null ? priceListModelsReadPriceListPrice.priceListName == null : this.priceListName.equals(priceListModelsReadPriceListPrice.priceListName)) &&
        (this.priceIncVat == null ? priceListModelsReadPriceListPrice.priceIncVat == null : this.priceIncVat.equals(priceListModelsReadPriceListPrice.priceIncVat)) &&
        (this.priceExVat == null ? priceListModelsReadPriceListPrice.priceExVat == null : this.priceExVat.equals(priceListModelsReadPriceListPrice.priceExVat)) &&
        (this.vatRate == null ? priceListModelsReadPriceListPrice.vatRate == null : this.vatRate.equals(priceListModelsReadPriceListPrice.vatRate)) &&
        (this.country == null ? priceListModelsReadPriceListPrice.country == null : this.country.equals(priceListModelsReadPriceListPrice.country)) &&
        (this.currency == null ? priceListModelsReadPriceListPrice.currency == null : this.currency.equals(priceListModelsReadPriceListPrice.currency)) &&
        (this.staggeredCount == null ? priceListModelsReadPriceListPrice.staggeredCount == null : this.staggeredCount.equals(priceListModelsReadPriceListPrice.staggeredCount)) &&
        (this.validFrom == null ? priceListModelsReadPriceListPrice.validFrom == null : this.validFrom.equals(priceListModelsReadPriceListPrice.validFrom)) &&
        (this.validTo == null ? priceListModelsReadPriceListPrice.validTo == null : this.validTo.equals(priceListModelsReadPriceListPrice.validTo));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.productId == null ? 0: this.productId.hashCode());
    result = 31 * result + (this.priceListId == null ? 0: this.priceListId.hashCode());
    result = 31 * result + (this.priceListName == null ? 0: this.priceListName.hashCode());
    result = 31 * result + (this.priceIncVat == null ? 0: this.priceIncVat.hashCode());
    result = 31 * result + (this.priceExVat == null ? 0: this.priceExVat.hashCode());
    result = 31 * result + (this.vatRate == null ? 0: this.vatRate.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.staggeredCount == null ? 0: this.staggeredCount.hashCode());
    result = 31 * result + (this.validFrom == null ? 0: this.validFrom.hashCode());
    result = 31 * result + (this.validTo == null ? 0: this.validTo.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceListModelsReadPriceListPrice {\n");
    
    sb.append("  productId: ").append(productId).append("\n");
    sb.append("  priceListId: ").append(priceListId).append("\n");
    sb.append("  priceListName: ").append(priceListName).append("\n");
    sb.append("  priceIncVat: ").append(priceIncVat).append("\n");
    sb.append("  priceExVat: ").append(priceExVat).append("\n");
    sb.append("  vatRate: ").append(vatRate).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  staggeredCount: ").append(staggeredCount).append("\n");
    sb.append("  validFrom: ").append(validFrom).append("\n");
    sb.append("  validTo: ").append(validTo).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
