/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.PriceListModelsWritePriceListPrice;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * The response of a PriceListPrice request.
 **/
@ApiModel(description = "The response of a PriceListPrice request.")
public class PriceListModelsPriceListPriceResponse {
  
  @SerializedName("Message")
  private String message = null;
  @SerializedName("Invalid")
  private List<PriceListModelsWritePriceListPrice> invalid = null;
  @SerializedName("NotFound")
  private List<PriceListModelsWritePriceListPrice> notFound = null;
  @SerializedName("UpdateCount")
  private Integer updateCount = null;

  /**
   * Information about the outcome of the request.
   **/
  @ApiModelProperty(value = "Information about the outcome of the request.")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   * Supplied PriceList prices that failed validation.
   **/
  @ApiModelProperty(value = "Supplied PriceList prices that failed validation.")
  public List<PriceListModelsWritePriceListPrice> getInvalid() {
    return invalid;
  }
  public void setInvalid(List<PriceListModelsWritePriceListPrice> invalid) {
    this.invalid = invalid;
  }

  /**
   * Supplied PriceList prices that were technically valid, but couldn't be found.
   **/
  @ApiModelProperty(value = "Supplied PriceList prices that were technically valid, but couldn't be found.")
  public List<PriceListModelsWritePriceListPrice> getNotFound() {
    return notFound;
  }
  public void setNotFound(List<PriceListModelsWritePriceListPrice> notFound) {
    this.notFound = notFound;
  }

  /**
   * Number of price updates resulting from the request.
   **/
  @ApiModelProperty(value = "Number of price updates resulting from the request.")
  public Integer getUpdateCount() {
    return updateCount;
  }
  public void setUpdateCount(Integer updateCount) {
    this.updateCount = updateCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceListModelsPriceListPriceResponse priceListModelsPriceListPriceResponse = (PriceListModelsPriceListPriceResponse) o;
    return (this.message == null ? priceListModelsPriceListPriceResponse.message == null : this.message.equals(priceListModelsPriceListPriceResponse.message)) &&
        (this.invalid == null ? priceListModelsPriceListPriceResponse.invalid == null : this.invalid.equals(priceListModelsPriceListPriceResponse.invalid)) &&
        (this.notFound == null ? priceListModelsPriceListPriceResponse.notFound == null : this.notFound.equals(priceListModelsPriceListPriceResponse.notFound)) &&
        (this.updateCount == null ? priceListModelsPriceListPriceResponse.updateCount == null : this.updateCount.equals(priceListModelsPriceListPriceResponse.updateCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.invalid == null ? 0: this.invalid.hashCode());
    result = 31 * result + (this.notFound == null ? 0: this.notFound.hashCode());
    result = 31 * result + (this.updateCount == null ? 0: this.updateCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceListModelsPriceListPriceResponse {\n");
    
    sb.append("  message: ").append(message).append("\n");
    sb.append("  invalid: ").append(invalid).append("\n");
    sb.append("  notFound: ").append(notFound).append("\n");
    sb.append("  updateCount: ").append(updateCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
