/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A stock value for a product item
 **/
@ApiModel(description = "A stock value for a product item")
public class ProductModelsWriteProductItemStock {
  
  @SerializedName("Id")
  private String id = null;
  @SerializedName("Stock")
  private Integer stock = null;
  @SerializedName("StockSellable")
  private Integer stockSellable = null;
  public enum StockTypeEnum {
     0,  1,  2, 
  };
  @SerializedName("StockType")
  private StockTypeEnum stockType = null;

  /**
   * A value to uniquely identity a single product item.  <remarks>This value can represent different fields, depending on configuration.</remarks>
   **/
  @ApiModelProperty(value = "A value to uniquely identity a single product item.  <remarks>This value can represent different fields, depending on configuration.</remarks>")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * The stock value.
   **/
  @ApiModelProperty(value = "The stock value.")
  public Integer getStock() {
    return stock;
  }
  public void setStock(Integer stock) {
    this.stock = stock;
  }

  /**
   * The sellable stock value.  <remarks>This value is read only.</remarks>
   **/
  @ApiModelProperty(value = "The sellable stock value.  <remarks>This value is read only.</remarks>")
  public Integer getStockSellable() {
    return stockSellable;
  }
  public void setStockSellable(Integer stockSellable) {
    this.stockSellable = stockSellable;
  }

  /**
   * The type of stock to be updated. See {Product.Models.ProductItemStockType}
   **/
  @ApiModelProperty(value = "The type of stock to be updated. See {Product.Models.ProductItemStockType}")
  public StockTypeEnum getStockType() {
    return stockType;
  }
  public void setStockType(StockTypeEnum stockType) {
    this.stockType = stockType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductModelsWriteProductItemStock productModelsWriteProductItemStock = (ProductModelsWriteProductItemStock) o;
    return (this.id == null ? productModelsWriteProductItemStock.id == null : this.id.equals(productModelsWriteProductItemStock.id)) &&
        (this.stock == null ? productModelsWriteProductItemStock.stock == null : this.stock.equals(productModelsWriteProductItemStock.stock)) &&
        (this.stockSellable == null ? productModelsWriteProductItemStock.stockSellable == null : this.stockSellable.equals(productModelsWriteProductItemStock.stockSellable)) &&
        (this.stockType == null ? productModelsWriteProductItemStock.stockType == null : this.stockType.equals(productModelsWriteProductItemStock.stockType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.stock == null ? 0: this.stock.hashCode());
    result = 31 * result + (this.stockSellable == null ? 0: this.stockSellable.hashCode());
    result = 31 * result + (this.stockType == null ? 0: this.stockType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductModelsWriteProductItemStock {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  stock: ").append(stock).append("\n");
    sb.append("  stockSellable: ").append(stockSellable).append("\n");
    sb.append("  stockType: ").append(stockType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
