/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A shipping fee for a product item.
 **/
@ApiModel(description = "A shipping fee for a product item.")
public class ProductModelsReadShippingFee {
  
  @SerializedName("Market")
  private Integer market = null;
  @SerializedName("Country")
  private String country = null;
  @SerializedName("Service")
  private String service = null;
  @SerializedName("ServiceId")
  private Integer serviceId = null;
  @SerializedName("Fee")
  private Double fee = null;

  /**
   * The market that the shipping fee is applicable on.
   **/
  @ApiModelProperty(value = "The market that the shipping fee is applicable on.")
  public Integer getMarket() {
    return market;
  }
  public void setMarket(Integer market) {
    this.market = market;
  }

  /**
   * The country that the shipping fee is applicable in.
   **/
  @ApiModelProperty(value = "The country that the shipping fee is applicable in.")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   * The shipping service with the current fee.
   **/
  @ApiModelProperty(value = "The shipping service with the current fee.")
  public String getService() {
    return service;
  }
  public void setService(String service) {
    this.service = service;
  }

  /**
   * The shipping service id with the current fee.
   **/
  @ApiModelProperty(value = "The shipping service id with the current fee.")
  public Integer getServiceId() {
    return serviceId;
  }
  public void setServiceId(Integer serviceId) {
    this.serviceId = serviceId;
  }

  /**
   * The shipping fee.
   **/
  @ApiModelProperty(value = "The shipping fee.")
  public Double getFee() {
    return fee;
  }
  public void setFee(Double fee) {
    this.fee = fee;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductModelsReadShippingFee productModelsReadShippingFee = (ProductModelsReadShippingFee) o;
    return (this.market == null ? productModelsReadShippingFee.market == null : this.market.equals(productModelsReadShippingFee.market)) &&
        (this.country == null ? productModelsReadShippingFee.country == null : this.country.equals(productModelsReadShippingFee.country)) &&
        (this.service == null ? productModelsReadShippingFee.service == null : this.service.equals(productModelsReadShippingFee.service)) &&
        (this.serviceId == null ? productModelsReadShippingFee.serviceId == null : this.serviceId.equals(productModelsReadShippingFee.serviceId)) &&
        (this.fee == null ? productModelsReadShippingFee.fee == null : this.fee.equals(productModelsReadShippingFee.fee));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.market == null ? 0: this.market.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.service == null ? 0: this.service.hashCode());
    result = 31 * result + (this.serviceId == null ? 0: this.serviceId.hashCode());
    result = 31 * result + (this.fee == null ? 0: this.fee.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductModelsReadShippingFee {\n");
    
    sb.append("  market: ").append(market).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  service: ").append(service).append("\n");
    sb.append("  serviceId: ").append(serviceId).append("\n");
    sb.append("  fee: ").append(fee).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
