/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductModelsMonitorSku {
  
  @SerializedName("SiteId")
  private Integer siteId = null;
  @SerializedName("LanguageCode")
  private String languageCode = null;
  @SerializedName("Email")
  private String email = null;
  @SerializedName("SkuId")
  private Integer skuId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSiteId() {
    return siteId;
  }
  public void setSiteId(Integer siteId) {
    this.siteId = siteId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLanguageCode() {
    return languageCode;
  }
  public void setLanguageCode(String languageCode) {
    this.languageCode = languageCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSkuId() {
    return skuId;
  }
  public void setSkuId(Integer skuId) {
    this.skuId = skuId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductModelsMonitorSku productModelsMonitorSku = (ProductModelsMonitorSku) o;
    return (this.siteId == null ? productModelsMonitorSku.siteId == null : this.siteId.equals(productModelsMonitorSku.siteId)) &&
        (this.languageCode == null ? productModelsMonitorSku.languageCode == null : this.languageCode.equals(productModelsMonitorSku.languageCode)) &&
        (this.email == null ? productModelsMonitorSku.email == null : this.email.equals(productModelsMonitorSku.email)) &&
        (this.skuId == null ? productModelsMonitorSku.skuId == null : this.skuId.equals(productModelsMonitorSku.skuId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.siteId == null ? 0: this.siteId.hashCode());
    result = 31 * result + (this.languageCode == null ? 0: this.languageCode.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.skuId == null ? 0: this.skuId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductModelsMonitorSku {\n");
    
    sb.append("  siteId: ").append(siteId).append("\n");
    sb.append("  languageCode: ").append(languageCode).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  skuId: ").append(skuId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
