/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A product item belonging to a product.
 **/
@ApiModel(description = "A product item belonging to a product.")
public class ProductModelsWriteProductItem {
  
  @SerializedName("ItemId")
  private Integer itemId = null;
  @SerializedName("ArticleNumber")
  private String articleNumber = null;
  @SerializedName("Name")
  private String name = null;
  @SerializedName("Shelf")
  private String shelf = null;
  @SerializedName("Weight")
  private Integer weight = null;
  @SerializedName("Length")
  private Integer length = null;
  @SerializedName("Width")
  private Integer width = null;
  @SerializedName("Height")
  private Integer height = null;
  @SerializedName("Gtin")
  private String gtin = null;
  @SerializedName("Active")
  private Boolean active = null;
  @SerializedName("ExternalId")
  private String externalId = null;

  /**
   * Id of the product item.
   **/
  @ApiModelProperty(value = "Id of the product item.")
  public Integer getItemId() {
    return itemId;
  }
  public void setItemId(Integer itemId) {
    this.itemId = itemId;
  }

  /**
   * The article number for the product item.
   **/
  @ApiModelProperty(value = "The article number for the product item.")
  public String getArticleNumber() {
    return articleNumber;
  }
  public void setArticleNumber(String articleNumber) {
    this.articleNumber = articleNumber;
  }

  /**
   * The name of the product item.
   **/
  @ApiModelProperty(value = "The name of the product item.")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * The shelf name where the product item can be found.
   **/
  @ApiModelProperty(value = "The shelf name where the product item can be found.")
  public String getShelf() {
    return shelf;
  }
  public void setShelf(String shelf) {
    this.shelf = shelf;
  }

  /**
   * The weight of the item in grams (g).
   **/
  @ApiModelProperty(value = "The weight of the item in grams (g).")
  public Integer getWeight() {
    return weight;
  }
  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  /**
   * The length of the item in millimeters (mm).
   **/
  @ApiModelProperty(value = "The length of the item in millimeters (mm).")
  public Integer getLength() {
    return length;
  }
  public void setLength(Integer length) {
    this.length = length;
  }

  /**
   * The width of the item in millimeters (mm).
   **/
  @ApiModelProperty(value = "The width of the item in millimeters (mm).")
  public Integer getWidth() {
    return width;
  }
  public void setWidth(Integer width) {
    this.width = width;
  }

  /**
   * The height of the item in millimeters (mm).
   **/
  @ApiModelProperty(value = "The height of the item in millimeters (mm).")
  public Integer getHeight() {
    return height;
  }
  public void setHeight(Integer height) {
    this.height = height;
  }

  /**
   * The GTIN number for the item.
   **/
  @ApiModelProperty(value = "The GTIN number for the item.")
  public String getGtin() {
    return gtin;
  }
  public void setGtin(String gtin) {
    this.gtin = gtin;
  }

  /**
   * The current state of the item.
   **/
  @ApiModelProperty(value = "The current state of the item.")
  public Boolean getActive() {
    return active;
  }
  public void setActive(Boolean active) {
    this.active = active;
  }

  /**
   * External Id of the product item.
   **/
  @ApiModelProperty(value = "External Id of the product item.")
  public String getExternalId() {
    return externalId;
  }
  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductModelsWriteProductItem productModelsWriteProductItem = (ProductModelsWriteProductItem) o;
    return (this.itemId == null ? productModelsWriteProductItem.itemId == null : this.itemId.equals(productModelsWriteProductItem.itemId)) &&
        (this.articleNumber == null ? productModelsWriteProductItem.articleNumber == null : this.articleNumber.equals(productModelsWriteProductItem.articleNumber)) &&
        (this.name == null ? productModelsWriteProductItem.name == null : this.name.equals(productModelsWriteProductItem.name)) &&
        (this.shelf == null ? productModelsWriteProductItem.shelf == null : this.shelf.equals(productModelsWriteProductItem.shelf)) &&
        (this.weight == null ? productModelsWriteProductItem.weight == null : this.weight.equals(productModelsWriteProductItem.weight)) &&
        (this.length == null ? productModelsWriteProductItem.length == null : this.length.equals(productModelsWriteProductItem.length)) &&
        (this.width == null ? productModelsWriteProductItem.width == null : this.width.equals(productModelsWriteProductItem.width)) &&
        (this.height == null ? productModelsWriteProductItem.height == null : this.height.equals(productModelsWriteProductItem.height)) &&
        (this.gtin == null ? productModelsWriteProductItem.gtin == null : this.gtin.equals(productModelsWriteProductItem.gtin)) &&
        (this.active == null ? productModelsWriteProductItem.active == null : this.active.equals(productModelsWriteProductItem.active)) &&
        (this.externalId == null ? productModelsWriteProductItem.externalId == null : this.externalId.equals(productModelsWriteProductItem.externalId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.itemId == null ? 0: this.itemId.hashCode());
    result = 31 * result + (this.articleNumber == null ? 0: this.articleNumber.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.shelf == null ? 0: this.shelf.hashCode());
    result = 31 * result + (this.weight == null ? 0: this.weight.hashCode());
    result = 31 * result + (this.length == null ? 0: this.length.hashCode());
    result = 31 * result + (this.width == null ? 0: this.width.hashCode());
    result = 31 * result + (this.height == null ? 0: this.height.hashCode());
    result = 31 * result + (this.gtin == null ? 0: this.gtin.hashCode());
    result = 31 * result + (this.active == null ? 0: this.active.hashCode());
    result = 31 * result + (this.externalId == null ? 0: this.externalId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductModelsWriteProductItem {\n");
    
    sb.append("  itemId: ").append(itemId).append("\n");
    sb.append("  articleNumber: ").append(articleNumber).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  shelf: ").append(shelf).append("\n");
    sb.append("  weight: ").append(weight).append("\n");
    sb.append("  length: ").append(length).append("\n");
    sb.append("  width: ").append(width).append("\n");
    sb.append("  height: ").append(height).append("\n");
    sb.append("  gtin: ").append(gtin).append("\n");
    sb.append("  active: ").append(active).append("\n");
    sb.append("  externalId: ").append(externalId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
