/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A product feed.
 **/
@ApiModel(description = "A product feed.")
public class ProductModelsReadFeed {
  
  @SerializedName("FeedId")
  private Integer feedId = null;
  @SerializedName("Name")
  private String name = null;
  @SerializedName("Url")
  private String url = null;
  @SerializedName("Layout")
  private String layout = null;
  @SerializedName("Market")
  private Integer market = null;
  @SerializedName("Language")
  private String language = null;
  @SerializedName("DefaultCurrency")
  private String defaultCurrency = null;
  @SerializedName("DefaultCountry")
  private String defaultCountry = null;

  /**
   * The feed id.
   **/
  @ApiModelProperty(value = "The feed id.")
  public Integer getFeedId() {
    return feedId;
  }
  public void setFeedId(Integer feedId) {
    this.feedId = feedId;
  }

  /**
   * The feed name.
   **/
  @ApiModelProperty(value = "The feed name.")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * The url to the feed.
   **/
  @ApiModelProperty(value = "The url to the feed.")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * The name of the feed layout.
   **/
  @ApiModelProperty(value = "The name of the feed layout.")
  public String getLayout() {
    return layout;
  }
  public void setLayout(String layout) {
    this.layout = layout;
  }

  /**
   * The market of the feed.
   **/
  @ApiModelProperty(value = "The market of the feed.")
  public Integer getMarket() {
    return market;
  }
  public void setMarket(Integer market) {
    this.market = market;
  }

  /**
   * The language code of the feed.
   **/
  @ApiModelProperty(value = "The language code of the feed.")
  public String getLanguage() {
    return language;
  }
  public void setLanguage(String language) {
    this.language = language;
  }

  /**
   * The default currency for the market
   **/
  @ApiModelProperty(value = "The default currency for the market")
  public String getDefaultCurrency() {
    return defaultCurrency;
  }
  public void setDefaultCurrency(String defaultCurrency) {
    this.defaultCurrency = defaultCurrency;
  }

  /**
   * The default country for the market
   **/
  @ApiModelProperty(value = "The default country for the market")
  public String getDefaultCountry() {
    return defaultCountry;
  }
  public void setDefaultCountry(String defaultCountry) {
    this.defaultCountry = defaultCountry;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductModelsReadFeed productModelsReadFeed = (ProductModelsReadFeed) o;
    return (this.feedId == null ? productModelsReadFeed.feedId == null : this.feedId.equals(productModelsReadFeed.feedId)) &&
        (this.name == null ? productModelsReadFeed.name == null : this.name.equals(productModelsReadFeed.name)) &&
        (this.url == null ? productModelsReadFeed.url == null : this.url.equals(productModelsReadFeed.url)) &&
        (this.layout == null ? productModelsReadFeed.layout == null : this.layout.equals(productModelsReadFeed.layout)) &&
        (this.market == null ? productModelsReadFeed.market == null : this.market.equals(productModelsReadFeed.market)) &&
        (this.language == null ? productModelsReadFeed.language == null : this.language.equals(productModelsReadFeed.language)) &&
        (this.defaultCurrency == null ? productModelsReadFeed.defaultCurrency == null : this.defaultCurrency.equals(productModelsReadFeed.defaultCurrency)) &&
        (this.defaultCountry == null ? productModelsReadFeed.defaultCountry == null : this.defaultCountry.equals(productModelsReadFeed.defaultCountry));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.feedId == null ? 0: this.feedId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.layout == null ? 0: this.layout.hashCode());
    result = 31 * result + (this.market == null ? 0: this.market.hashCode());
    result = 31 * result + (this.language == null ? 0: this.language.hashCode());
    result = 31 * result + (this.defaultCurrency == null ? 0: this.defaultCurrency.hashCode());
    result = 31 * result + (this.defaultCountry == null ? 0: this.defaultCountry.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductModelsReadFeed {\n");
    
    sb.append("  feedId: ").append(feedId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  layout: ").append(layout).append("\n");
    sb.append("  market: ").append(market).append("\n");
    sb.append("  language: ").append(language).append("\n");
    sb.append("  defaultCurrency: ").append(defaultCurrency).append("\n");
    sb.append("  defaultCountry: ").append(defaultCountry).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
