/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.SharedModelsLocalizableContent;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A parameter value for a product.
 **/
@ApiModel(description = "A parameter value for a product.")
public class ProductParameterModelsWriteProductParameterValue {
  
  @SerializedName("ProductId")
  private Integer productId = null;
  @SerializedName("ParameterId")
  private Integer parameterId = null;
  @SerializedName("Value")
  private String value = null;
  @SerializedName("LocalizedDescriptions")
  private List<SharedModelsLocalizableContent> localizedDescriptions = null;

  /**
   * The product id of the parameter.
   **/
  @ApiModelProperty(value = "The product id of the parameter.")
  public Integer getProductId() {
    return productId;
  }
  public void setProductId(Integer productId) {
    this.productId = productId;
  }

  /**
   * The unique identifier of the parameter that this value belongs to.
   **/
  @ApiModelProperty(value = "The unique identifier of the parameter that this value belongs to.")
  public Integer getParameterId() {
    return parameterId;
  }
  public void setParameterId(Integer parameterId) {
    this.parameterId = parameterId;
  }

  /**
   * The identifying value of the parameter.
   **/
  @ApiModelProperty(value = "The identifying value of the parameter.")
  public String getValue() {
    return value;
  }
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * The localized descriptions of the parameter.
   **/
  @ApiModelProperty(value = "The localized descriptions of the parameter.")
  public List<SharedModelsLocalizableContent> getLocalizedDescriptions() {
    return localizedDescriptions;
  }
  public void setLocalizedDescriptions(List<SharedModelsLocalizableContent> localizedDescriptions) {
    this.localizedDescriptions = localizedDescriptions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductParameterModelsWriteProductParameterValue productParameterModelsWriteProductParameterValue = (ProductParameterModelsWriteProductParameterValue) o;
    return (this.productId == null ? productParameterModelsWriteProductParameterValue.productId == null : this.productId.equals(productParameterModelsWriteProductParameterValue.productId)) &&
        (this.parameterId == null ? productParameterModelsWriteProductParameterValue.parameterId == null : this.parameterId.equals(productParameterModelsWriteProductParameterValue.parameterId)) &&
        (this.value == null ? productParameterModelsWriteProductParameterValue.value == null : this.value.equals(productParameterModelsWriteProductParameterValue.value)) &&
        (this.localizedDescriptions == null ? productParameterModelsWriteProductParameterValue.localizedDescriptions == null : this.localizedDescriptions.equals(productParameterModelsWriteProductParameterValue.localizedDescriptions));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.productId == null ? 0: this.productId.hashCode());
    result = 31 * result + (this.parameterId == null ? 0: this.parameterId.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    result = 31 * result + (this.localizedDescriptions == null ? 0: this.localizedDescriptions.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductParameterModelsWriteProductParameterValue {\n");
    
    sb.append("  productId: ").append(productId).append("\n");
    sb.append("  parameterId: ").append(parameterId).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("  localizedDescriptions: ").append(localizedDescriptions).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
