/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.SharedModelsLocalizableContent;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A parameter value for a product.
 **/
@ApiModel(description = "A parameter value for a product.")
public class ProductParameterModelsReadProductParameterValue {
  
  @SerializedName("ParameterValueId")
  private Integer parameterValueId = null;
  @SerializedName("ProductId")
  private Integer productId = null;
  @SerializedName("ParameterId")
  private Integer parameterId = null;
  @SerializedName("ParameterName")
  private String parameterName = null;
  @SerializedName("GroupId")
  private Integer groupId = null;
  @SerializedName("GroupName")
  private String groupName = null;
  public enum ParameterTypeEnum {
     1,  2,  3,  4,  5,  6,  7, 
  };
  @SerializedName("ParameterType")
  private ParameterTypeEnum parameterType = null;
  @SerializedName("Value")
  private String value = null;
  @SerializedName("Description")
  private String description = null;
  @SerializedName("LocalizedDescriptions")
  private List<SharedModelsLocalizableContent> localizedDescriptions = null;
  @SerializedName("InternalIdentifier")
  private String internalIdentifier = null;

  /**
   * The unique identifier of this parameter value.
   **/
  @ApiModelProperty(value = "The unique identifier of this parameter value.")
  public Integer getParameterValueId() {
    return parameterValueId;
  }
  public void setParameterValueId(Integer parameterValueId) {
    this.parameterValueId = parameterValueId;
  }

  /**
   * The product id of the parameter.
   **/
  @ApiModelProperty(value = "The product id of the parameter.")
  public Integer getProductId() {
    return productId;
  }
  public void setProductId(Integer productId) {
    this.productId = productId;
  }

  /**
   * The unique identifier of the parameter that this value belongs to.
   **/
  @ApiModelProperty(value = "The unique identifier of the parameter that this value belongs to.")
  public Integer getParameterId() {
    return parameterId;
  }
  public void setParameterId(Integer parameterId) {
    this.parameterId = parameterId;
  }

  /**
   * The non-localized name of the parameter.
   **/
  @ApiModelProperty(value = "The non-localized name of the parameter.")
  public String getParameterName() {
    return parameterName;
  }
  public void setParameterName(String parameterName) {
    this.parameterName = parameterName;
  }

  /**
   * The unique identifier of the group that this parameter belongs to.
   **/
  @ApiModelProperty(value = "The unique identifier of the group that this parameter belongs to.")
  public Integer getGroupId() {
    return groupId;
  }
  public void setGroupId(Integer groupId) {
    this.groupId = groupId;
  }

  /**
   * The name of the group that this parameter belongs to.
   **/
  @ApiModelProperty(value = "The name of the group that this parameter belongs to.")
  public String getGroupName() {
    return groupName;
  }
  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  /**
   * The type of parameter.
   **/
  @ApiModelProperty(value = "The type of parameter.")
  public ParameterTypeEnum getParameterType() {
    return parameterType;
  }
  public void setParameterType(ParameterTypeEnum parameterType) {
    this.parameterType = parameterType;
  }

  /**
   * The identifying value of the parameter.
   **/
  @ApiModelProperty(value = "The identifying value of the parameter.")
  public String getValue() {
    return value;
  }
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * The non-localized description of the parameter.
   **/
  @ApiModelProperty(value = "The non-localized description of the parameter.")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * The localized descriptions of the parameter.
   **/
  @ApiModelProperty(value = "The localized descriptions of the parameter.")
  public List<SharedModelsLocalizableContent> getLocalizedDescriptions() {
    return localizedDescriptions;
  }
  public void setLocalizedDescriptions(List<SharedModelsLocalizableContent> localizedDescriptions) {
    this.localizedDescriptions = localizedDescriptions;
  }

  /**
   * The internal identifier of the parameter.
   **/
  @ApiModelProperty(value = "The internal identifier of the parameter.")
  public String getInternalIdentifier() {
    return internalIdentifier;
  }
  public void setInternalIdentifier(String internalIdentifier) {
    this.internalIdentifier = internalIdentifier;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductParameterModelsReadProductParameterValue productParameterModelsReadProductParameterValue = (ProductParameterModelsReadProductParameterValue) o;
    return (this.parameterValueId == null ? productParameterModelsReadProductParameterValue.parameterValueId == null : this.parameterValueId.equals(productParameterModelsReadProductParameterValue.parameterValueId)) &&
        (this.productId == null ? productParameterModelsReadProductParameterValue.productId == null : this.productId.equals(productParameterModelsReadProductParameterValue.productId)) &&
        (this.parameterId == null ? productParameterModelsReadProductParameterValue.parameterId == null : this.parameterId.equals(productParameterModelsReadProductParameterValue.parameterId)) &&
        (this.parameterName == null ? productParameterModelsReadProductParameterValue.parameterName == null : this.parameterName.equals(productParameterModelsReadProductParameterValue.parameterName)) &&
        (this.groupId == null ? productParameterModelsReadProductParameterValue.groupId == null : this.groupId.equals(productParameterModelsReadProductParameterValue.groupId)) &&
        (this.groupName == null ? productParameterModelsReadProductParameterValue.groupName == null : this.groupName.equals(productParameterModelsReadProductParameterValue.groupName)) &&
        (this.parameterType == null ? productParameterModelsReadProductParameterValue.parameterType == null : this.parameterType.equals(productParameterModelsReadProductParameterValue.parameterType)) &&
        (this.value == null ? productParameterModelsReadProductParameterValue.value == null : this.value.equals(productParameterModelsReadProductParameterValue.value)) &&
        (this.description == null ? productParameterModelsReadProductParameterValue.description == null : this.description.equals(productParameterModelsReadProductParameterValue.description)) &&
        (this.localizedDescriptions == null ? productParameterModelsReadProductParameterValue.localizedDescriptions == null : this.localizedDescriptions.equals(productParameterModelsReadProductParameterValue.localizedDescriptions)) &&
        (this.internalIdentifier == null ? productParameterModelsReadProductParameterValue.internalIdentifier == null : this.internalIdentifier.equals(productParameterModelsReadProductParameterValue.internalIdentifier));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.parameterValueId == null ? 0: this.parameterValueId.hashCode());
    result = 31 * result + (this.productId == null ? 0: this.productId.hashCode());
    result = 31 * result + (this.parameterId == null ? 0: this.parameterId.hashCode());
    result = 31 * result + (this.parameterName == null ? 0: this.parameterName.hashCode());
    result = 31 * result + (this.groupId == null ? 0: this.groupId.hashCode());
    result = 31 * result + (this.groupName == null ? 0: this.groupName.hashCode());
    result = 31 * result + (this.parameterType == null ? 0: this.parameterType.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.localizedDescriptions == null ? 0: this.localizedDescriptions.hashCode());
    result = 31 * result + (this.internalIdentifier == null ? 0: this.internalIdentifier.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductParameterModelsReadProductParameterValue {\n");
    
    sb.append("  parameterValueId: ").append(parameterValueId).append("\n");
    sb.append("  productId: ").append(productId).append("\n");
    sb.append("  parameterId: ").append(parameterId).append("\n");
    sb.append("  parameterName: ").append(parameterName).append("\n");
    sb.append("  groupId: ").append(groupId).append("\n");
    sb.append("  groupName: ").append(groupName).append("\n");
    sb.append("  parameterType: ").append(parameterType).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  localizedDescriptions: ").append(localizedDescriptions).append("\n");
    sb.append("  internalIdentifier: ").append(internalIdentifier).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
