/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A piece of localized content.
 **/
@ApiModel(description = "A piece of localized content.")
public class SharedModelsLocalizableContent {
  
  @SerializedName("LanguageCode")
  private String languageCode = null;
  @SerializedName("Content")
  private String content = null;

  /**
   * The 2-letter ISO 639-1 language code for this locale.
   **/
  @ApiModelProperty(value = "The 2-letter ISO 639-1 language code for this locale.")
  public String getLanguageCode() {
    return languageCode;
  }
  public void setLanguageCode(String languageCode) {
    this.languageCode = languageCode;
  }

  /**
   * The localized content.
   **/
  @ApiModelProperty(value = "The localized content.")
  public String getContent() {
    return content;
  }
  public void setContent(String content) {
    this.content = content;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SharedModelsLocalizableContent sharedModelsLocalizableContent = (SharedModelsLocalizableContent) o;
    return (this.languageCode == null ? sharedModelsLocalizableContent.languageCode == null : this.languageCode.equals(sharedModelsLocalizableContent.languageCode)) &&
        (this.content == null ? sharedModelsLocalizableContent.content == null : this.content.equals(sharedModelsLocalizableContent.content));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.languageCode == null ? 0: this.languageCode.hashCode());
    result = 31 * result + (this.content == null ? 0: this.content.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SharedModelsLocalizableContent {\n");
    
    sb.append("  languageCode: ").append(languageCode).append("\n");
    sb.append("  content: ").append(content).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
