/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Creation options for new parcel groups.
 **/
@ApiModel(description = "Creation options for new parcel groups.")
public class ShippingModelsParcelGroupOptions {
  
  @SerializedName("OrderIds")
  private List<Integer> orderIds = null;
  @SerializedName("MarkAsDelivered")
  private Boolean markAsDelivered = null;
  @SerializedName("SignalCapturesCreated")
  private Boolean signalCapturesCreated = null;

  /**
   * The order ids contained in this parcel group.
   **/
  @ApiModelProperty(value = "The order ids contained in this parcel group.")
  public List<Integer> getOrderIds() {
    return orderIds;
  }
  public void setOrderIds(List<Integer> orderIds) {
    this.orderIds = orderIds;
  }

  /**
   * Set to true to also automatically mark orders as delivered upon creation of the parcel group.
   **/
  @ApiModelProperty(value = "Set to true to also automatically mark orders as delivered upon creation of the parcel group.")
  public Boolean getMarkAsDelivered() {
    return markAsDelivered;
  }
  public void setMarkAsDelivered(Boolean markAsDelivered) {
    this.markAsDelivered = markAsDelivered;
  }

  /**
   * Set to true to also automatically signal capture events upon creation of the parcel group.
   **/
  @ApiModelProperty(value = "Set to true to also automatically signal capture events upon creation of the parcel group.")
  public Boolean getSignalCapturesCreated() {
    return signalCapturesCreated;
  }
  public void setSignalCapturesCreated(Boolean signalCapturesCreated) {
    this.signalCapturesCreated = signalCapturesCreated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShippingModelsParcelGroupOptions shippingModelsParcelGroupOptions = (ShippingModelsParcelGroupOptions) o;
    return (this.orderIds == null ? shippingModelsParcelGroupOptions.orderIds == null : this.orderIds.equals(shippingModelsParcelGroupOptions.orderIds)) &&
        (this.markAsDelivered == null ? shippingModelsParcelGroupOptions.markAsDelivered == null : this.markAsDelivered.equals(shippingModelsParcelGroupOptions.markAsDelivered)) &&
        (this.signalCapturesCreated == null ? shippingModelsParcelGroupOptions.signalCapturesCreated == null : this.signalCapturesCreated.equals(shippingModelsParcelGroupOptions.signalCapturesCreated));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.orderIds == null ? 0: this.orderIds.hashCode());
    result = 31 * result + (this.markAsDelivered == null ? 0: this.markAsDelivered.hashCode());
    result = 31 * result + (this.signalCapturesCreated == null ? 0: this.signalCapturesCreated.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShippingModelsParcelGroupOptions {\n");
    
    sb.append("  orderIds: ").append(orderIds).append("\n");
    sb.append("  markAsDelivered: ").append(markAsDelivered).append("\n");
    sb.append("  signalCapturesCreated: ").append(signalCapturesCreated).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
