/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A supplier query.
 **/
@ApiModel(description = "A supplier query.")
public class SupplierModelsSupplierQuery {
  
  @SerializedName("NameContains")
  private String nameContains = null;
  @SerializedName("ExternalIds")
  private List<String> externalIds = null;

  /**
   * Limits query to suppliers with a name containing the specified string.
   **/
  @ApiModelProperty(value = "Limits query to suppliers with a name containing the specified string.")
  public String getNameContains() {
    return nameContains;
  }
  public void setNameContains(String nameContains) {
    this.nameContains = nameContains;
  }

  /**
   * Limits query to externalIds
   **/
  @ApiModelProperty(value = "Limits query to externalIds")
  public List<String> getExternalIds() {
    return externalIds;
  }
  public void setExternalIds(List<String> externalIds) {
    this.externalIds = externalIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupplierModelsSupplierQuery supplierModelsSupplierQuery = (SupplierModelsSupplierQuery) o;
    return (this.nameContains == null ? supplierModelsSupplierQuery.nameContains == null : this.nameContains.equals(supplierModelsSupplierQuery.nameContains)) &&
        (this.externalIds == null ? supplierModelsSupplierQuery.externalIds == null : this.externalIds.equals(supplierModelsSupplierQuery.externalIds));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.nameContains == null ? 0: this.nameContains.hashCode());
    result = 31 * result + (this.externalIds == null ? 0: this.externalIds.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupplierModelsSupplierQuery {\n");
    
    sb.append("  nameContains: ").append(nameContains).append("\n");
    sb.append("  externalIds: ").append(externalIds).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
