/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Map;
import org.openapitools.client.model.ContainerRestrictionSetupContainerRestrictionConfiguration;
import org.openapitools.client.model.PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration;
import org.openapitools.client.model.PageWidgetLazyLoadSetupLazyLoadConfiguration;
import org.openapitools.client.model.WidgetRestrictionSetupWidgetRestrictionConfiguration;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SystemNullableValidationConfiguration {
  
  @SerializedName("LazyLoadConfiguration")
  private PageWidgetLazyLoadSetupLazyLoadConfiguration lazyLoadConfiguration = null;
  @SerializedName("LazyLoadCollectionConfigurations")
  private List<PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration> lazyLoadCollectionConfigurations = null;
  @SerializedName("WidgetRestrictions")
  private Map<String, WidgetRestrictionSetupWidgetRestrictionConfiguration> widgetRestrictions = null;
  @SerializedName("ContainerRestrictions")
  private ContainerRestrictionSetupContainerRestrictionConfiguration containerRestrictions = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public PageWidgetLazyLoadSetupLazyLoadConfiguration getLazyLoadConfiguration() {
    return lazyLoadConfiguration;
  }
  public void setLazyLoadConfiguration(PageWidgetLazyLoadSetupLazyLoadConfiguration lazyLoadConfiguration) {
    this.lazyLoadConfiguration = lazyLoadConfiguration;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration> getLazyLoadCollectionConfigurations() {
    return lazyLoadCollectionConfigurations;
  }
  public void setLazyLoadCollectionConfigurations(List<PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration> lazyLoadCollectionConfigurations) {
    this.lazyLoadCollectionConfigurations = lazyLoadCollectionConfigurations;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, WidgetRestrictionSetupWidgetRestrictionConfiguration> getWidgetRestrictions() {
    return widgetRestrictions;
  }
  public void setWidgetRestrictions(Map<String, WidgetRestrictionSetupWidgetRestrictionConfiguration> widgetRestrictions) {
    this.widgetRestrictions = widgetRestrictions;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ContainerRestrictionSetupContainerRestrictionConfiguration getContainerRestrictions() {
    return containerRestrictions;
  }
  public void setContainerRestrictions(ContainerRestrictionSetupContainerRestrictionConfiguration containerRestrictions) {
    this.containerRestrictions = containerRestrictions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemNullableValidationConfiguration systemNullableValidationConfiguration = (SystemNullableValidationConfiguration) o;
    return (this.lazyLoadConfiguration == null ? systemNullableValidationConfiguration.lazyLoadConfiguration == null : this.lazyLoadConfiguration.equals(systemNullableValidationConfiguration.lazyLoadConfiguration)) &&
        (this.lazyLoadCollectionConfigurations == null ? systemNullableValidationConfiguration.lazyLoadCollectionConfigurations == null : this.lazyLoadCollectionConfigurations.equals(systemNullableValidationConfiguration.lazyLoadCollectionConfigurations)) &&
        (this.widgetRestrictions == null ? systemNullableValidationConfiguration.widgetRestrictions == null : this.widgetRestrictions.equals(systemNullableValidationConfiguration.widgetRestrictions)) &&
        (this.containerRestrictions == null ? systemNullableValidationConfiguration.containerRestrictions == null : this.containerRestrictions.equals(systemNullableValidationConfiguration.containerRestrictions));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.lazyLoadConfiguration == null ? 0: this.lazyLoadConfiguration.hashCode());
    result = 31 * result + (this.lazyLoadCollectionConfigurations == null ? 0: this.lazyLoadCollectionConfigurations.hashCode());
    result = 31 * result + (this.widgetRestrictions == null ? 0: this.widgetRestrictions.hashCode());
    result = 31 * result + (this.containerRestrictions == null ? 0: this.containerRestrictions.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemNullableValidationConfiguration {\n");
    
    sb.append("  lazyLoadConfiguration: ").append(lazyLoadConfiguration).append("\n");
    sb.append("  lazyLoadCollectionConfigurations: ").append(lazyLoadCollectionConfigurations).append("\n");
    sb.append("  widgetRestrictions: ").append(widgetRestrictions).append("\n");
    sb.append("  containerRestrictions: ").append(containerRestrictions).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
