/**
 * Geins Management API
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserModelsWriteUserProfile {
  
  @SerializedName("UserId")
  private Integer userId = null;
  @SerializedName("SiteId")
  private Integer siteId = null;
  @SerializedName("Email")
  private String email = null;
  @SerializedName("Password")
  private String password = null;
  @SerializedName("FirstName")
  private String firstName = null;
  @SerializedName("LastName")
  private String lastName = null;
  @SerializedName("PhoneNr")
  private String phoneNr = null;
  @SerializedName("MobilePhoneNr")
  private String mobilePhoneNr = null;
  @SerializedName("Company")
  private String company = null;
  @SerializedName("UserTypeId")
  private Integer userTypeId = null;
  @SerializedName("Address")
  private String address = null;
  @SerializedName("Address2")
  private String address2 = null;
  @SerializedName("Address3")
  private String address3 = null;
  @SerializedName("DoorCode")
  private String doorCode = null;
  @SerializedName("PersonalId")
  private String personalId = null;
  @SerializedName("Birthyear")
  private String birthyear = null;
  @SerializedName("Zip")
  private String zip = null;
  @SerializedName("City")
  private String city = null;
  @SerializedName("CareOf")
  private String careOf = null;
  @SerializedName("Country")
  private String country = null;
  @SerializedName("CountryId")
  private Integer countryId = null;
  @SerializedName("Gender")
  private Boolean gender = null;
  @SerializedName("Newsletter")
  private Boolean newsletter = null;
  @SerializedName("HasExternalAuth")
  private Boolean hasExternalAuth = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getUserId() {
    return userId;
  }
  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSiteId() {
    return siteId;
  }
  public void setSiteId(Integer siteId) {
    this.siteId = siteId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPhoneNr() {
    return phoneNr;
  }
  public void setPhoneNr(String phoneNr) {
    this.phoneNr = phoneNr;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMobilePhoneNr() {
    return mobilePhoneNr;
  }
  public void setMobilePhoneNr(String mobilePhoneNr) {
    this.mobilePhoneNr = mobilePhoneNr;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCompany() {
    return company;
  }
  public void setCompany(String company) {
    this.company = company;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getUserTypeId() {
    return userTypeId;
  }
  public void setUserTypeId(Integer userTypeId) {
    this.userTypeId = userTypeId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAddress2() {
    return address2;
  }
  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAddress3() {
    return address3;
  }
  public void setAddress3(String address3) {
    this.address3 = address3;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDoorCode() {
    return doorCode;
  }
  public void setDoorCode(String doorCode) {
    this.doorCode = doorCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPersonalId() {
    return personalId;
  }
  public void setPersonalId(String personalId) {
    this.personalId = personalId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBirthyear() {
    return birthyear;
  }
  public void setBirthyear(String birthyear) {
    this.birthyear = birthyear;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getZip() {
    return zip;
  }
  public void setZip(String zip) {
    this.zip = zip;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCareOf() {
    return careOf;
  }
  public void setCareOf(String careOf) {
    this.careOf = careOf;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCountryId() {
    return countryId;
  }
  public void setCountryId(Integer countryId) {
    this.countryId = countryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getGender() {
    return gender;
  }
  public void setGender(Boolean gender) {
    this.gender = gender;
  }

  /**
   * Decides whether the user should be subscribed to the newsletter.
   **/
  @ApiModelProperty(value = "Decides whether the user should be subscribed to the newsletter.")
  public Boolean getNewsletter() {
    return newsletter;
  }
  public void setNewsletter(Boolean newsletter) {
    this.newsletter = newsletter;
  }

  /**
   * Set this to true if the management platform will not be the main way of authentication.
   **/
  @ApiModelProperty(value = "Set this to true if the management platform will not be the main way of authentication.")
  public Boolean getHasExternalAuth() {
    return hasExternalAuth;
  }
  public void setHasExternalAuth(Boolean hasExternalAuth) {
    this.hasExternalAuth = hasExternalAuth;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserModelsWriteUserProfile userModelsWriteUserProfile = (UserModelsWriteUserProfile) o;
    return (this.userId == null ? userModelsWriteUserProfile.userId == null : this.userId.equals(userModelsWriteUserProfile.userId)) &&
        (this.siteId == null ? userModelsWriteUserProfile.siteId == null : this.siteId.equals(userModelsWriteUserProfile.siteId)) &&
        (this.email == null ? userModelsWriteUserProfile.email == null : this.email.equals(userModelsWriteUserProfile.email)) &&
        (this.password == null ? userModelsWriteUserProfile.password == null : this.password.equals(userModelsWriteUserProfile.password)) &&
        (this.firstName == null ? userModelsWriteUserProfile.firstName == null : this.firstName.equals(userModelsWriteUserProfile.firstName)) &&
        (this.lastName == null ? userModelsWriteUserProfile.lastName == null : this.lastName.equals(userModelsWriteUserProfile.lastName)) &&
        (this.phoneNr == null ? userModelsWriteUserProfile.phoneNr == null : this.phoneNr.equals(userModelsWriteUserProfile.phoneNr)) &&
        (this.mobilePhoneNr == null ? userModelsWriteUserProfile.mobilePhoneNr == null : this.mobilePhoneNr.equals(userModelsWriteUserProfile.mobilePhoneNr)) &&
        (this.company == null ? userModelsWriteUserProfile.company == null : this.company.equals(userModelsWriteUserProfile.company)) &&
        (this.userTypeId == null ? userModelsWriteUserProfile.userTypeId == null : this.userTypeId.equals(userModelsWriteUserProfile.userTypeId)) &&
        (this.address == null ? userModelsWriteUserProfile.address == null : this.address.equals(userModelsWriteUserProfile.address)) &&
        (this.address2 == null ? userModelsWriteUserProfile.address2 == null : this.address2.equals(userModelsWriteUserProfile.address2)) &&
        (this.address3 == null ? userModelsWriteUserProfile.address3 == null : this.address3.equals(userModelsWriteUserProfile.address3)) &&
        (this.doorCode == null ? userModelsWriteUserProfile.doorCode == null : this.doorCode.equals(userModelsWriteUserProfile.doorCode)) &&
        (this.personalId == null ? userModelsWriteUserProfile.personalId == null : this.personalId.equals(userModelsWriteUserProfile.personalId)) &&
        (this.birthyear == null ? userModelsWriteUserProfile.birthyear == null : this.birthyear.equals(userModelsWriteUserProfile.birthyear)) &&
        (this.zip == null ? userModelsWriteUserProfile.zip == null : this.zip.equals(userModelsWriteUserProfile.zip)) &&
        (this.city == null ? userModelsWriteUserProfile.city == null : this.city.equals(userModelsWriteUserProfile.city)) &&
        (this.careOf == null ? userModelsWriteUserProfile.careOf == null : this.careOf.equals(userModelsWriteUserProfile.careOf)) &&
        (this.country == null ? userModelsWriteUserProfile.country == null : this.country.equals(userModelsWriteUserProfile.country)) &&
        (this.countryId == null ? userModelsWriteUserProfile.countryId == null : this.countryId.equals(userModelsWriteUserProfile.countryId)) &&
        (this.gender == null ? userModelsWriteUserProfile.gender == null : this.gender.equals(userModelsWriteUserProfile.gender)) &&
        (this.newsletter == null ? userModelsWriteUserProfile.newsletter == null : this.newsletter.equals(userModelsWriteUserProfile.newsletter)) &&
        (this.hasExternalAuth == null ? userModelsWriteUserProfile.hasExternalAuth == null : this.hasExternalAuth.equals(userModelsWriteUserProfile.hasExternalAuth));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.siteId == null ? 0: this.siteId.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.phoneNr == null ? 0: this.phoneNr.hashCode());
    result = 31 * result + (this.mobilePhoneNr == null ? 0: this.mobilePhoneNr.hashCode());
    result = 31 * result + (this.company == null ? 0: this.company.hashCode());
    result = 31 * result + (this.userTypeId == null ? 0: this.userTypeId.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    result = 31 * result + (this.address2 == null ? 0: this.address2.hashCode());
    result = 31 * result + (this.address3 == null ? 0: this.address3.hashCode());
    result = 31 * result + (this.doorCode == null ? 0: this.doorCode.hashCode());
    result = 31 * result + (this.personalId == null ? 0: this.personalId.hashCode());
    result = 31 * result + (this.birthyear == null ? 0: this.birthyear.hashCode());
    result = 31 * result + (this.zip == null ? 0: this.zip.hashCode());
    result = 31 * result + (this.city == null ? 0: this.city.hashCode());
    result = 31 * result + (this.careOf == null ? 0: this.careOf.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.countryId == null ? 0: this.countryId.hashCode());
    result = 31 * result + (this.gender == null ? 0: this.gender.hashCode());
    result = 31 * result + (this.newsletter == null ? 0: this.newsletter.hashCode());
    result = 31 * result + (this.hasExternalAuth == null ? 0: this.hasExternalAuth.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserModelsWriteUserProfile {\n");
    
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  siteId: ").append(siteId).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  phoneNr: ").append(phoneNr).append("\n");
    sb.append("  mobilePhoneNr: ").append(mobilePhoneNr).append("\n");
    sb.append("  company: ").append(company).append("\n");
    sb.append("  userTypeId: ").append(userTypeId).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("  address2: ").append(address2).append("\n");
    sb.append("  address3: ").append(address3).append("\n");
    sb.append("  doorCode: ").append(doorCode).append("\n");
    sb.append("  personalId: ").append(personalId).append("\n");
    sb.append("  birthyear: ").append(birthyear).append("\n");
    sb.append("  zip: ").append(zip).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  careOf: ").append(careOf).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  countryId: ").append(countryId).append("\n");
    sb.append("  gender: ").append(gender).append("\n");
    sb.append("  newsletter: ").append(newsletter).append("\n");
    sb.append("  hasExternalAuth: ").append(hasExternalAuth).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
